In [5]:
import cv2 as cv
import numpy as np

filename=r'C:\Users\luoyongchen\Pictures\lena.jpg'
src=cv.imread(filename) 
cv.namedWindow("input", cv.WINDOW_AUTOSIZE)
cv.imshow("input", src)
gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)

# 转换为浮点数类型数组
gray = np.float32(gray)
print(gray)

# scale and shift by NORM_MINMAX
dst = np.zeros(gray.shape, dtype=np.float32)
output=cv.normalize(gray, dst=dst, alpha=0, beta=1.0, norm_type=cv.NORM_MINMAX)
print('output',output)
print('dst',dst)            #output=dst
cv.imshow("NORM_MINMAX", np.uint8(dst*255)) 

# scale and shift by NORM_INF
dst = np.zeros(gray.shape, dtype=np.float32)
cv.normalize(gray, dst=dst, alpha=1.0, beta=0, norm_type=cv.NORM_INF)
print(dst)
cv.imshow("NORM_INF", np.uint8(dst*255))

# scale and shift by NORM_L1
dst = np.zeros(gray.shape, dtype=np.float32)
cv.normalize(gray, dst=dst, alpha=1.0, beta=0, norm_type=cv.NORM_L1)
print(dst)
cv.imshow("NORM_L1", np.uint8(dst*10000000))

# scale and shift by NORM_L2
dst = np.zeros(gray.shape, dtype=np.float32)
cv.normalize(gray, dst=dst, alpha=1.0, beta=0, norm_type=cv.NORM_L2)
print(dst)
cv.imshow("NORM_L2", np.uint8(dst*10000))
cv.waitKey()
cv.destroyAllWindows()

[[160. 161. 161. ... 174. 169. 145.]
 [160. 160. 161. ... 179. 172. 147.]
 [159. 160. 160. ... 157. 142. 115.]
 ...
 [ 48.  57.  53. ...  78.  89.  97.]
 [ 46.  55.  51. ...  90.  98. 103.]
 [ 41.  50.  47. ... 100. 105. 107.]]
output [[0.64732146 0.6517858  0.6517858  ... 0.70982146 0.68750006 0.5803572 ]
 [0.64732146 0.64732146 0.6517858  ... 0.7321429  0.7008929  0.58928573]
 [0.6428572  0.64732146 0.64732146 ... 0.6339286  0.5669643  0.44642857]
 ...
 [0.14732143 0.1875     0.16964287 ... 0.28125    0.33035713 0.36607143]
 [0.13839287 0.17857143 0.1607143  ... 0.33482143 0.37053573 0.39285716]
 [0.11607143 0.15625    0.14285713 ... 0.3794643  0.40178573 0.4107143 ]]
dst [[0.64732146 0.6517858  0.6517858  ... 0.70982146 0.68750006 0.5803572 ]
 [0.64732146 0.64732146 0.6517858  ... 0.7321429  0.7008929  0.58928573]
 [0.6428572  0.64732146 0.64732146 ... 0.6339286  0.5669643  0.44642857]
 ...
 [0.14732143 0.1875     0.16964287 ... 0.28125    0.33035713 0.36607143]
 [0.13839287 0.17857