In [5]:
import cv2 as cv
import numpy as np

def connected_components_demo(src):
    src = cv.GaussianBlur(src, (3, 3), 0)
    gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
    ret, binary = cv.threshold(gray, 0, 255, cv.THRESH_BINARY | cv.THRESH_OTSU)
    cv.imshow("binary", binary)

    output = cv.connectedComponents(binary, connectivity=8, ltype=cv.CV_32S)#输出两个结果
    num_labels = output[0]   #output的第一个参数，表示总共的标记的个数
    print(num_labels )
    labels = output[1]        #output的第二个参数，表示
    cv.imshow('labels',labels)
    print(labels,labels.shape)
    colors = []              #初始化颜色值
    for i in range(num_labels):       
        b = np.random.randint(0, 256)
        g = np.random.randint(0, 256)
        r = np.random.randint(0, 256)
        colors.append((b, g, r))

    colors[0] = (0, 0, 0)           #背景标记为黑色
    h, w = gray.shape
    image = np.zeros((h, w, 3), dtype=np.uint8)
    #遍历整个灰度图
    for row in range(h):
        for col in range(w):
            image[row, col] = colors[labels[row, col]]

    cv.imshow("colored labels", image)
    print("total rice : ", num_labels - 1)    #减去背景的那一个label

file=r'C:\Users\luo yong chen\Pictures\rice.png'
src=cv.imread(file)
print(src.shape)
h, w = src.shape[:2]
connected_components_demo(src)
cv.waitKey(0)
cv.destroyAllWindows()

(442, 756, 3)
26
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] (442, 756)
total rice :  25
