In [8]:
import cv2 as cv
import numpy as np

file=r'C:\Users\luo yong chen\Pictures\hand.jpg'
src=cv.imread(file1)
cv.namedWindow("input", cv.WINDOW_AUTOSIZE)
cv.imshow("input", src)
gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
ret, binary = cv.threshold(gray, 0, 255, cv.THRESH_BINARY | cv.THRESH_OTSU)
k = cv.getStructuringElement(cv.MORPH_RECT, (3, 3))
binary = cv.morphologyEx(binary, cv.MORPH_OPEN, k)
cv.imshow("binary", binary)

# 轮廓发现
out, contours, hierarchy = cv.findContours(binary, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)
for c in range(len(contours)):
    ret = cv.isContourConvex(contours[c])
    points = cv.convexHull(contours[c])             #points是三维数组
    total = len(points)
    for i in range(len(points)):
        x1, y1 = points[i%total][0]
        x2, y2 = points[(i+1)%total][0]
        cv.circle(src, (x1, y1), 4, (255, 0, 0), 2, 8, 0)
        cv.line(src, (x1, y1), (x2, y2), (0, 0, 255), 2, 8, 0)
    print(total)           #输出最外层的点的个数
    print(points)          #输出最外层的点的坐标
    print("convex : ", ret)

# 显示
cv.imshow("contours_analysis", src)
cv.waitKey(0)
cv.destroyAllWindows()

28
[[[438 295]]

 [[436 299]]

 [[356 399]]

 [[313 451]]

 [[249 520]]

 [[152 520]]

 [[121 442]]

 [[113 421]]

 [[109 409]]

 [[106 397]]

 [[100 371]]

 [[ 97 356]]

 [[ 75 219]]

 [[ 74 212]]

 [[ 74 202]]

 [[ 75 199]]

 [[ 77 195]]

 [[126 126]]

 [[132 120]]

 [[173  80]]

 [[177  77]]

 [[181  75]]

 [[192  75]]

 [[252 103]]

 [[255 105]]

 [[434 283]]

 [[436 285]]

 [[438 289]]]
convex :  False
