In [15]:
import cv2 as cv
import numpy as np

def canny_demo(image):
    t = 80
    canny_output = cv.Canny(image, t, t * 2)
    return canny_output

file=r'C:\Users\luo yong chen\Pictures\morph01.png'
src=cv.imread(file)
cv.imshow("input", src)
binary = canny_demo(src)
cv.imshow("binary", binary)

linesP = cv.HoughLinesP(binary, 1, np.pi / 180, 50, None, 50, 10)#minLineLength=50，maxLineGap=10，
print(linesP)

drawing=np.zeros(src.shape,dtype=np.uint8)
if linesP is not None:
    for i in range(0, len(linesP)):
        l = linesP[i][0]
        cv.line(drawing, (l[0], l[1]), (l[2], l[3]), (255, 255, 0), 1, cv.LINE_AA)

# 显示
cv.imshow("hough detect", drawing)
cv.waitKey(0)
cv.destroyAllWindows()

[[[ 19 114 372 114]]

 [[ 21  69 374  69]]

 [[ 19 111 372 111]]

 [[ 19  65 376  65]]

 [[ 50 240  50  14]]

 [[ 46 240  46  14]]

 [[162 147 360 147]]

 [[162 144 360 144]]

 [[ 90 148  90  10]]

 [[141 242 141 122]]

 [[238 213 294 213]]

 [[ 86 150  86   8]]

 [[128 126 128  11]]

 [[145 244 145 120]]

 [[124 125 124  11]]

 [[280 195 336 195]]

 [[160 209 235 210]]

 [[254 197 350 197]]

 [[237 211 310 211]]

 [[158 196 253 196]]

 [[158 194 254 194]]]
