In [26]:
import cv2 as cv
import numpy as np

file1=r'C:\Users\luo yong chen\Pictures\coins.jpg'
src1=cv.imread(file1)
cv.imshow("input", src1)
gray1 = cv.cvtColor(src1, cv.COLOR_BGR2GRAY)
cv.imshow('gray',gray1)
gray = cv.GaussianBlur(gray1, (9, 9), 2, 2)

file2=r'C:\Users\luo yong chen\Pictures\circles.png'
src2=cv.imread(file2)
cv.imshow("input", src2)
gray2 = cv.cvtColor(src2, cv.COLOR_BGR2GRAY)
cv.imshow('gray',gray2)
gray2 = cv.GaussianBlur(gray2, (9, 9), 2, 2)


dp_1 = 2     #dp对检测的结果有很大的影响
param1_1 = 100
param2_1 = 100          
circles1 = cv.HoughCircles(gray, cv.HOUGH_GRADIENT, dp_1, 10, None, param1_1, param2_1, 20, 100)
for c in circles1[0,:]:
    print(c)
    cx, cy, r = c
    cv.circle(src1, (cx, cy), 2, (0, 255, 0), 2, 8, 0)#绘制圆心
    cv.circle(src1, (cx, cy), r, (0, 0, 255), 2, 8, 0)#绘制圆的轮廓
    
#练手，调参
dp_2 = 2.1   #dp对检测的结果有很大的影响
param1_2 = 100
param2_2 = 100          #更改成80会得到凭空检测出来的圆
circles2 = cv.HoughCircles(gray, cv.HOUGH_GRADIENT, dp_2, 10, None, param1_2, param2_2, 20, 100)
for c in circles2[0,:]:
    print(c)
    cx, cy, r = c
    cv.circle(src2, (cx, cy), 2, (0, 255, 0), 2, 8, 0)#绘制圆心
    cv.circle(src2, (cx, cy), r, (0, 0, 255), 2, 8, 0)#绘制圆的轮廓
    
# 显示
cv.imshow("hough circle detect1", src1)
cv.imshow("hough circle detect2", src2)

cv.waitKey(0)
cv.destroyAllWindows()

[217.  105.   41.6]
[305. 121.  30.]
[257.  235.   39.4]
[327.  189.   39.2]
[193.  181.   41.6]
[323. 257.  30.]
[141. 115.  37.]
[187.  253.   30.4]
[261.  161.   30.6]
[139.65     114.45      36.379997]
[192.15 181.65  41.  ]
[326.55 187.95  41.  ]
[255.15    236.24998  41.     ]
[217.34999  106.049995  41.      ]
[305.55     120.74999   29.029999]
[200.54999 173.24998  52.55   ]
[261.44998 162.75     29.45   ]
[206.84999 162.75     47.93   ]
[324.44998 257.25     30.29   ]
[187.95    250.94998  29.24   ]
[217.34999 156.45     52.55   ]
[208.95      99.74999   31.759998]
[242.54999 244.65     54.86   ]
[227.84999  99.74999  31.55   ]
[225.74998  175.34999   31.759998]
