In [3]:
import cv2 as cv
import numpy as np

file=r'C:\Users\luo yong chen\Pictures\st_02.png'
src=cv.imread(file)
cv.namedWindow("input", cv.WINDOW_AUTOSIZE)
cv.imshow("input", src)

# 图像二值化
gray = cv.cvtColor(src, cv.COLOR_BGR2GRAY)
ret, binary = cv.threshold(gray, 0, 255, cv.THRESH_BINARY_INV | cv.THRESH_OTSU)

se = cv.getStructuringElement(cv.MORPH_RECT, (3, 3), (-1, -1))
binary = cv.morphologyEx(binary, cv.MORPH_OPEN, se)
cv.imshow("binary", binary)
#cv.imwrite("D:/binary.png", binary)

# 轮廓提取, 发现最大轮廓
out, contours, hierarchy = cv.findContours(binary, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE)
index = 0
max = 0
for c in range(len(contours)):
    area = cv.contourArea(contours[c])
    if area > max:
        max = area
        index = c

# 寻找最小外接矩形
rect = cv.minAreaRect(contours[index])
print(rect[2])
print(rect[0])
# trick
height, width = rect[1]
print(rect[1])
box = cv.boxPoints(rect)
src_pts = np.int0(box)
print(src_pts)

dst_pts = []
dst_pts.append([width,height])
dst_pts.append([0, height])
dst_pts.append([0, 0])
dst_pts.append([width, 0])

# 透视变换
M, status = cv.findHomography(src_pts, np.array(dst_pts))#找到两个平面之间的转换矩阵
print(M)
result = cv.warpPerspective(src, M, (np.int32(width), np.int32(height)))

if height < width:
    result = cv.rotate(result, cv.ROTATE_90_CLOCKWISE)

cv.imshow("result", result)


cv.waitKey(0)
cv.destroyAllWindows()

-40.00936508178711
(415.9403076171875, 405.6201171875)
(667.0657958984375, 500.1227722167969)
[[321 811]
 [  0 428]
 [510   0]
 [832 382]]
[[ 6.45668919e-01  7.69371843e-01 -3.29291149e+02]
 [-7.67203161e-01  6.46700047e-01  3.91273612e+02]
 [ 2.44305757e-06  3.48659099e-06  1.00000000e+00]]
