In [1]:
import numpy as np
import cv2 as cv

def process(image, opt=1):
    # Detecting corners
    gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    corners = cv.goodFeaturesToTrack(gray, 100, 0.05, 10)
    print(len(corners))
    for pt in corners:
        print(pt)
        b = np.random.randint(0, 256)
        g = np.random.randint(0, 256)
        r = np.random.randint(0, 256)
        x = np.int32(pt[0][0])
        y = np.int32(pt[0][1])
        cv.circle(image, (x, y), 5, (int(b), int(g), int(r)), 2)
    # output
    return image

file=r'C:\Users\luo yong chen\Pictures\color_object.mp4'
cap= cv.VideoCapture(file)

while True:
    ret, frame = cap.read()
    if ret is True:
        cv.imshow('input', frame)
        result = process(frame)
        cv.imshow('result', result)
        k = cv.waitKey(50)&0xff
        if k == 27:
            break
    else:
        break
cap.release()
cv.destroyAllWindows()

20
[[147. 446.]]
[[277. 461.]]
[[267. 460.]]
[[114. 446.]]
[[121. 429.]]
[[411. 475.]]
[[  7. 454.]]
[[135. 394.]]
[[ 98. 355.]]
[[131. 431.]]
[[141. 379.]]
[[124. 441.]]
[[285. 478.]]
[[ 64. 476.]]
[[138. 414.]]
[[101. 450.]]
[[ 81. 463.]]
[[ 76. 316.]]
[[136. 347.]]
[[315. 369.]]
15
[[148. 445.]]
[[277. 461.]]
[[267. 461.]]
[[411. 476.]]
[[121. 427.]]
[[ 98. 355.]]
[[136. 428.]]
[[124. 441.]]
[[ 10. 454.]]
[[ 66. 473.]]
[[285. 478.]]
[[ 79. 462.]]
[[ 76. 316.]]
[[135. 394.]]
[[113. 446.]]
9
[[148. 445.]]
[[277. 461.]]
[[267. 460.]]
[[ 67. 472.]]
[[124. 441.]]
[[135. 432.]]
[[284. 478.]]
[[120. 428.]]
[[138. 414.]]
11
[[148. 445.]]
[[277. 461.]]
[[267. 460.]]
[[123. 441.]]
[[120. 428.]]
[[136. 429.]]
[[285. 478.]]
[[100. 451.]]
[[  7. 454.]]
[[138. 415.]]
[[ 64. 475.]]
9
[[148. 445.]]
[[277. 461.]]
[[267. 461.]]
[[122. 427.]]
[[124. 441.]]
[[136. 412.]]
[[285. 478.]]
[[  7. 454.]]
[[409. 475.]]
17
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[122. 427.]]
[[124. 441.]]
[[136. 412.]]
[[  

20
[[148. 445.]]
[[503. 166.]]
[[277. 461.]]
[[420. 107.]]
[[464. 141.]]
[[266. 461.]]
[[476. 161.]]
[[121. 427.]]
[[382.  77.]]
[[533. 304.]]
[[464. 127.]]
[[452. 138.]]
[[359.  60.]]
[[ 66. 472.]]
[[376. 468.]]
[[ 11. 454.]]
[[136. 429.]]
[[411. 476.]]
[[113. 421.]]
[[134. 398.]]
38
[[148. 445.]]
[[502. 163.]]
[[277. 460.]]
[[267. 461.]]
[[474. 163.]]
[[463. 143.]]
[[451. 139.]]
[[533. 199.]]
[[354.  64.]]
[[418. 109.]]
[[120. 428.]]
[[461. 127.]]
[[412. 476.]]
[[382.  78.]]
[[531. 303.]]
[[122. 442.]]
[[ 11. 454.]]
[[135. 428.]]
[[138. 414.]]
[[ 66. 472.]]
[[492. 171.]]
[[ 76. 315.]]
[[428. 116.]]
[[638. 357.]]
[[ 98. 353.]]
[[526. 209.]]
[[ 76. 464.]]
[[472. 125.]]
[[452. 190.]]
[[382.  64.]]
[[135. 346.]]
[[ 89. 452.]]
[[440. 136.]]
[[565. 324.]]
[[376. 468.]]
[[140. 375.]]
[[407. 401.]]
[[306. 450.]]
19
[[148. 445.]]
[[499. 163.]]
[[277. 461.]]
[[534. 199.]]
[[267. 461.]]
[[488. 173.]]
[[138. 414.]]
[[417. 111.]]
[[285. 478.]]
[[451. 140.]]
[[519. 217.]]
[[382.  81.]]
[[516. 206.

14
[[148. 445.]]
[[277. 460.]]
[[267. 461.]]
[[135. 430.]]
[[ 66. 471.]]
[[122. 427.]]
[[123. 441.]]
[[306. 451.]]
[[285. 478.]]
[[ 76. 316.]]
[[  7. 454.]]
[[139. 418.]]
[[372. 232.]]
[[101. 413.]]
16
[[147. 446.]]
[[277. 460.]]
[[267. 461.]]
[[  8. 453.]]
[[123. 441.]]
[[373. 218.]]
[[135. 432.]]
[[136. 412.]]
[[ 66. 472.]]
[[285. 478.]]
[[ 79. 463.]]
[[117. 424.]]
[[434. 253.]]
[[ 97. 355.]]
[[434. 235.]]
[[306. 450.]]
15
[[147. 446.]]
[[277. 461.]]
[[267. 461.]]
[[131. 431.]]
[[123. 441.]]
[[138. 414.]]
[[120. 428.]]
[[  7. 453.]]
[[285. 478.]]
[[ 66. 472.]]
[[306. 450.]]
[[114. 410.]]
[[144. 435.]]
[[ 79. 463.]]
[[ 96. 356.]]
12
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[138. 414.]]
[[  8. 453.]]
[[ 66. 472.]]
[[285. 478.]]
[[124. 441.]]
[[120. 429.]]
[[130. 431.]]
[[560. 396.]]
[[ 98. 355.]]
15
[[147. 446.]]
[[267. 461.]]
[[277. 461.]]
[[  8. 453.]]
[[121. 427.]]
[[124. 441.]]
[[138. 414.]]
[[136. 429.]]
[[140. 377.]]
[[228.  71.]]
[[412. 476.]]
[[ 66. 472.]]
[[110. 447.]]
[[ 98

[[267. 461.]]
[[412. 476.]]
[[506. 409.]]
[[ 66. 472.]]
[[619. 443.]]
[[427. 425.]]
[[  7. 453.]]
[[138. 414.]]
[[284. 478.]]
[[120. 428.]]
[[441. 378.]]
[[539. 421.]]
[[123. 439.]]
[[ 97. 355.]]
[[132. 431.]]
17
[[148. 445.]]
[[277. 461.]]
[[267. 461.]]
[[412. 476.]]
[[506. 409.]]
[[ 66. 472.]]
[[619. 443.]]
[[427. 425.]]
[[  7. 453.]]
[[138. 414.]]
[[285. 478.]]
[[120. 428.]]
[[441. 378.]]
[[539. 421.]]
[[123. 439.]]
[[ 97. 355.]]
[[132. 431.]]
17
[[148. 445.]]
[[276. 460.]]
[[  7. 453.]]
[[120. 428.]]
[[285. 478.]]
[[412. 476.]]
[[440. 378.]]
[[138. 414.]]
[[470. 398.]]
[[531. 405.]]
[[ 66. 472.]]
[[155. 465.]]
[[131. 430.]]
[[428. 425.]]
[[125. 440.]]
[[ 97. 357.]]
[[ 87. 452.]]
11
[[148. 445.]]
[[277. 460.]]
[[267. 461.]]
[[120. 427.]]
[[285. 478.]]
[[124. 441.]]
[[411. 475.]]
[[138. 414.]]
[[ 11. 454.]]
[[131. 430.]]
[[ 64. 475.]]
15
[[148. 445.]]
[[277. 461.]]
[[411. 476.]]
[[267. 461.]]
[[ 10. 453.]]
[[284. 478.]]
[[120. 428.]]
[[455. 347.]]
[[138. 414.]]
[[130. 431.]]
[[548. 3

[[267. 461.]]
[[138. 414.]]
[[ 66. 472.]]
[[411. 475.]]
[[  6. 453.]]
[[120. 428.]]
[[285. 478.]]
[[123. 441.]]
[[131. 431.]]
[[100. 354.]]
[[ 78. 461.]]
14
[[148. 444.]]
[[277. 461.]]
[[266. 460.]]
[[ 67. 472.]]
[[411. 476.]]
[[138. 414.]]
[[118. 423.]]
[[285. 478.]]
[[124. 441.]]
[[  7. 453.]]
[[132. 431.]]
[[441. 422.]]
[[ 87. 452.]]
[[ 97. 355.]]
12
[[148. 444.]]
[[277. 460.]]
[[267. 461.]]
[[138. 414.]]
[[412. 476.]]
[[121. 427.]]
[[  6. 453.]]
[[285. 478.]]
[[ 66. 472.]]
[[123. 441.]]
[[132. 431.]]
[[432. 417.]]
11
[[148. 444.]]
[[277. 460.]]
[[267. 461.]]
[[138. 414.]]
[[412. 476.]]
[[121. 427.]]
[[  6. 453.]]
[[285. 478.]]
[[ 66. 472.]]
[[123. 441.]]
[[132. 431.]]
16
[[147. 445.]]
[[277. 461.]]
[[267. 461.]]
[[411. 476.]]
[[138. 414.]]
[[121. 427.]]
[[285. 478.]]
[[  6. 453.]]
[[132. 431.]]
[[ 64. 475.]]
[[123. 442.]]
[[108. 350.]]
[[ 79. 461.]]
[[ 98. 353.]]
[[117. 416.]]
[[340. 352.]]
13
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[ 66. 472.]]
[[  7. 453.]]
[[121. 427.]]
[[336

22
[[148. 445.]]
[[267. 460.]]
[[335. 312.]]
[[277. 460.]]
[[539. 373.]]
[[513. 462.]]
[[  7. 453.]]
[[124. 441.]]
[[261. 312.]]
[[122. 427.]]
[[412. 475.]]
[[211. 298.]]
[[266. 300.]]
[[304. 310.]]
[[ 67. 472.]]
[[136. 412.]]
[[ 79. 463.]]
[[155. 283.]]
[[136. 428.]]
[[552. 363.]]
[[388. 435.]]
[[ 97. 413.]]
26
[[147. 446.]]
[[267. 460.]]
[[277. 460.]]
[[261. 312.]]
[[511. 457.]]
[[298. 311.]]
[[412. 475.]]
[[537. 368.]]
[[  7. 453.]]
[[209. 298.]]
[[141. 384.]]
[[260. 300.]]
[[121. 427.]]
[[136. 412.]]
[[131. 431.]]
[[123. 442.]]
[[311. 350.]]
[[ 79. 463.]]
[[330. 311.]]
[[132. 401.]]
[[ 76. 315.]]
[[ 64. 475.]]
[[276. 346.]]
[[111. 349.]]
[[390. 434.]]
[[269. 319.]]
16
[[147. 446.]]
[[267. 460.]]
[[411. 475.]]
[[278. 460.]]
[[510. 451.]]
[[  7. 453.]]
[[135. 432.]]
[[121. 427.]]
[[123. 442.]]
[[ 79. 463.]]
[[536. 362.]]
[[ 80. 325.]]
[[139. 418.]]
[[135. 394.]]
[[ 64. 475.]]
[[ 76. 315.]]
16
[[148. 444.]]
[[267. 460.]]
[[411. 475.]]
[[278. 460.]]
[[510. 451.]]
[[ 10. 453.]]
[[135. 4

[[267. 461.]]
[[411. 475.]]
[[131. 431.]]
[[124. 441.]]
[[121. 427.]]
[[285. 478.]]
[[ 66. 472.]]
[[  7. 453.]]
[[136. 412.]]
[[ 79. 464.]]
[[569. 375.]]
[[ 89. 408.]]
[[ 98. 353.]]
13
[[148. 445.]]
[[277. 461.]]
[[267. 461.]]
[[411. 475.]]
[[136. 412.]]
[[120. 428.]]
[[ 10. 453.]]
[[136. 429.]]
[[285. 478.]]
[[ 98. 355.]]
[[ 66. 472.]]
[[123. 441.]]
[[ 79. 462.]]
15
[[148. 445.]]
[[277. 461.]]
[[267. 461.]]
[[411. 475.]]
[[122. 428.]]
[[  7. 453.]]
[[136. 412.]]
[[470. 315.]]
[[284. 478.]]
[[124. 441.]]
[[451. 357.]]
[[ 66. 472.]]
[[619. 434.]]
[[ 81. 464.]]
[[134. 430.]]
17
[[148. 445.]]
[[276. 460.]]
[[453. 362.]]
[[  8. 453.]]
[[624. 438.]]
[[285. 478.]]
[[411. 475.]]
[[121. 427.]]
[[134. 430.]]
[[136. 412.]]
[[582. 384.]]
[[472. 320.]]
[[ 62. 476.]]
[[ 79. 463.]]
[[123. 441.]]
[[562. 367.]]
[[100. 355.]]
17
[[148. 445.]]
[[276. 460.]]
[[453. 362.]]
[[  8. 453.]]
[[624. 438.]]
[[285. 478.]]
[[411. 475.]]
[[121. 427.]]
[[134. 430.]]
[[136. 412.]]
[[582. 384.]]
[[472. 320.]]
[[ 62. 4

[[418. 406.]]
[[444. 401.]]
[[  8. 453.]]
[[277. 461.]]
[[123. 441.]]
[[ 66. 472.]]
[[417. 390.]]
[[266. 460.]]
[[121. 427.]]
[[135. 432.]]
[[ 98. 356.]]
[[ 87. 452.]]
[[138. 414.]]
[[378. 397.]]
[[114. 446.]]
[[284. 478.]]
[[300. 368.]]
[[442. 378.]]
[[ 79. 462.]]
[[117. 416.]]
[[334. 388.]]
[[ 97. 413.]]
13
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[442. 396.]]
[[ 67. 472.]]
[[138. 414.]]
[[  7. 453.]]
[[412. 387.]]
[[118. 423.]]
[[131. 431.]]
[[ 97. 355.]]
[[135. 394.]]
[[387. 382.]]
20
[[148. 444.]]
[[442. 391.]]
[[277. 461.]]
[[267. 461.]]
[[282. 399.]]
[[390. 411.]]
[[  7. 453.]]
[[138. 414.]]
[[134. 430.]]
[[414. 393.]]
[[411. 380.]]
[[347. 399.]]
[[305. 452.]]
[[118. 423.]]
[[ 66. 472.]]
[[ 98. 356.]]
[[330. 366.]]
[[494. 432.]]
[[124. 441.]]
[[135. 394.]]
20
[[148. 444.]]
[[442. 391.]]
[[277. 461.]]
[[267. 461.]]
[[282. 399.]]
[[390. 411.]]
[[  7. 453.]]
[[138. 414.]]
[[134. 430.]]
[[414. 393.]]
[[411. 380.]]
[[347. 399.]]
[[305. 452.]]
[[118. 423.]]
[[ 66. 472.]]
[[330. 366.

[[452. 302.]]
[[510. 310.]]
[[443. 308.]]
[[316. 223.]]
[[267. 461.]]
[[411. 475.]]
[[  7. 453.]]
[[121. 427.]]
[[388. 208.]]
[[417. 357.]]
[[ 66. 472.]]
[[548. 431.]]
[[284. 478.]]
[[521. 420.]]
[[123. 442.]]
[[135. 432.]]
[[136. 412.]]
[[521. 384.]]
[[ 98. 354.]]
[[638. 446.]]
[[344. 261.]]
[[417. 251.]]
[[371. 187.]]
[[448. 335.]]
[[479. 311.]]
[[446. 322.]]
[[ 77. 463.]]
[[373. 398.]]
29
[[148. 445.]]
[[277. 461.]]
[[452. 302.]]
[[267. 461.]]
[[444. 308.]]
[[317. 223.]]
[[123. 441.]]
[[510. 311.]]
[[  7. 453.]]
[[120. 428.]]
[[409. 475.]]
[[136. 412.]]
[[131. 431.]]
[[285. 478.]]
[[548. 431.]]
[[466. 326.]]
[[416. 357.]]
[[496. 312.]]
[[484. 311.]]
[[521. 421.]]
[[417. 251.]]
[[ 79. 464.]]
[[449. 335.]]
[[505. 420.]]
[[364. 190.]]
[[ 61. 478.]]
[[ 96. 356.]]
[[388. 208.]]
[[521. 384.]]
35
[[148. 445.]]
[[444. 308.]]
[[277. 461.]]
[[452. 302.]]
[[317. 223.]]
[[267. 461.]]
[[ 11. 453.]]
[[510. 311.]]
[[285. 478.]]
[[120. 428.]]
[[ 64. 475.]]
[[448. 335.]]
[[522. 421.]]
[[123. 442.]]


[[267. 461.]]
[[530. 267.]]
[[411. 476.]]
[[121. 427.]]
[[  7. 453.]]
[[512. 237.]]
[[136. 410.]]
[[135. 395.]]
[[284. 478.]]
[[395. 151.]]
[[530. 280.]]
[[124. 441.]]
[[134. 430.]]
[[ 64. 475.]]
[[ 82. 458.]]
[[135. 347.]]
[[484. 226.]]
[[544. 247.]]
32
[[148. 445.]]
[[509. 245.]]
[[277. 461.]]
[[418. 156.]]
[[493. 226.]]
[[267. 461.]]
[[480. 233.]]
[[ 67. 472.]]
[[542. 252.]]
[[458. 276.]]
[[438. 256.]]
[[447. 204.]]
[[471. 228.]]
[[411. 475.]]
[[118. 423.]]
[[  6. 453.]]
[[131. 431.]]
[[417. 170.]]
[[138. 414.]]
[[285. 478.]]
[[ 79. 463.]]
[[123. 442.]]
[[391. 156.]]
[[ 97. 355.]]
[[499. 259.]]
[[490. 239.]]
[[135. 394.]]
[[369. 196.]]
[[469. 301.]]
[[ 87. 452.]]
[[466. 205.]]
[[552. 373.]]
29
[[148. 444.]]
[[509. 244.]]
[[277. 460.]]
[[267. 461.]]
[[417. 155.]]
[[458. 208.]]
[[ 66. 472.]]
[[541. 252.]]
[[490. 238.]]
[[458. 276.]]
[[414. 171.]]
[[492. 225.]]
[[479. 233.]]
[[448. 203.]]
[[437. 256.]]
[[  7. 453.]]
[[118. 423.]]
[[131. 431.]]
[[123. 441.]]
[[392. 154.]]
[[138. 414.]]


[[554. 202.]]
[[517. 220.]]
[[491. 188.]]
[[529. 187.]]
[[572. 240.]]
[[454. 184.]]
[[277. 460.]]
[[267. 461.]]
[[546. 160.]]
[[ 10. 453.]]
[[437. 229.]]
[[476. 219.]]
[[138. 414.]]
[[118. 423.]]
[[131. 431.]]
[[285. 478.]]
[[376. 198.]]
[[ 64. 475.]]
[[411. 475.]]
[[413. 205.]]
[[455. 194.]]
[[477. 177.]]
[[537. 223.]]
[[529. 212.]]
[[464. 201.]]
[[402. 199.]]
34
[[513. 179.]]
[[148. 444.]]
[[554. 202.]]
[[517. 220.]]
[[492. 187.]]
[[529. 187.]]
[[572. 239.]]
[[454. 184.]]
[[277. 460.]]
[[476. 219.]]
[[267. 461.]]
[[436. 230.]]
[[413. 205.]]
[[  7. 453.]]
[[138. 414.]]
[[544. 160.]]
[[455. 194.]]
[[376. 198.]]
[[477. 177.]]
[[411. 475.]]
[[136. 429.]]
[[285. 478.]]
[[513. 189.]]
[[538. 225.]]
[[ 66. 472.]]
[[529. 212.]]
[[120. 428.]]
[[125. 440.]]
[[503. 190.]]
[[423. 210.]]
[[100. 355.]]
[[412. 190.]]
[[593. 180.]]
[[ 81. 458.]]
33
[[148. 444.]]
[[513. 179.]]
[[554. 203.]]
[[517. 220.]]
[[572. 239.]]
[[529. 187.]]
[[454. 182.]]
[[277. 461.]]
[[267. 461.]]
[[543. 161.]]
[[476. 219.]]


[[267. 461.]]
[[411. 475.]]
[[131. 431.]]
[[120. 428.]]
[[ 10. 453.]]
[[124. 441.]]
[[322. 377.]]
[[ 66. 472.]]
[[442. 374.]]
[[285. 478.]]
[[139. 418.]]
[[509. 377.]]
[[155. 468.]]
[[378. 418.]]
[[ 97. 355.]]
[[306. 450.]]
[[139. 387.]]
12
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[121. 427.]]
[[412. 475.]]
[[138. 414.]]
[[130. 432.]]
[[  7. 453.]]
[[285. 478.]]
[[ 66. 472.]]
[[124. 443.]]
[[155. 468.]]
12
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[121. 427.]]
[[412. 475.]]
[[138. 414.]]
[[130. 432.]]
[[  7. 453.]]
[[285. 478.]]
[[ 66. 472.]]
[[124. 443.]]
[[155. 468.]]
13
[[148. 445.]]
[[277. 461.]]
[[411. 475.]]
[[267. 461.]]
[[  7. 453.]]
[[123. 441.]]
[[285. 478.]]
[[132. 431.]]
[[138. 414.]]
[[121. 427.]]
[[529. 324.]]
[[491. 318.]]
[[ 64. 475.]]
31
[[148. 444.]]
[[527. 320.]]
[[491. 317.]]
[[277. 461.]]
[[466. 323.]]
[[438. 310.]]
[[426. 322.]]
[[387. 320.]]
[[267. 461.]]
[[549. 353.]]
[[459. 310.]]
[[348. 308.]]
[[131. 431.]]
[[411. 475.]]
[[ 10. 453.]]
[[136. 412.]]
[[478. 3

[[554.  94.]]
[[592. 109.]]
[[612. 144.]]
[[568.  98.]]
[[526.  90.]]
[[570. 126.]]
[[277. 461.]]
[[533. 103.]]
[[557. 134.]]
[[267. 461.]]
[[602. 113.]]
[[411. 476.]]
[[  7. 453.]]
[[120. 428.]]
[[500. 109.]]
[[136. 431.]]
[[579.  72.]]
[[ 66. 472.]]
[[285. 478.]]
[[504.  98.]]
[[ 98. 355.]]
[[124. 443.]]
[[139. 418.]]
[[582. 178.]]
[[546. 105.]]
[[117. 416.]]
20
[[148. 444.]]
[[547.  98.]]
[[277. 461.]]
[[267. 461.]]
[[  7. 453.]]
[[412. 476.]]
[[ 66. 472.]]
[[610. 145.]]
[[ 78. 462.]]
[[118. 423.]]
[[566.  98.]]
[[130. 431.]]
[[422. 122.]]
[[285. 478.]]
[[585. 113.]]
[[489. 106.]]
[[122. 442.]]
[[576. 129.]]
[[139. 418.]]
[[572.  75.]]
28
[[547.  98.]]
[[148. 444.]]
[[584. 111.]]
[[559. 101.]]
[[526. 107.]]
[[277. 460.]]
[[489. 106.]]
[[515. 137.]]
[[267. 461.]]
[[594. 114.]]
[[604. 144.]]
[[411. 476.]]
[[553. 131.]]
[[519.  91.]]
[[511.  98.]]
[[120. 428.]]
[[ 66. 472.]]
[[  7. 453.]]
[[285. 478.]]
[[138. 414.]]
[[416. 123.]]
[[136. 429.]]
[[569.  75.]]
[[123. 442.]]
[[456. 124.]]


24
[[148. 445.]]
[[426. 285.]]
[[277. 461.]]
[[267. 461.]]
[[123. 441.]]
[[457. 290.]]
[[634. 419.]]
[[138. 414.]]
[[ 66. 472.]]
[[  7. 453.]]
[[118. 423.]]
[[285. 478.]]
[[ 87. 452.]]
[[136. 429.]]
[[395. 278.]]
[[411. 475.]]
[[ 78. 461.]]
[[434. 222.]]
[[450. 314.]]
[[107. 416.]]
[[109. 395.]]
[[251. 331.]]
[[416. 291.]]
[[135. 394.]]
24
[[148. 445.]]
[[277. 461.]]
[[267. 461.]]
[[118. 423.]]
[[138. 414.]]
[[393. 288.]]
[[299. 225.]]
[[627. 420.]]
[[136. 429.]]
[[378. 290.]]
[[285. 478.]]
[[  6. 454.]]
[[ 64. 475.]]
[[342. 255.]]
[[272. 212.]]
[[307. 448.]]
[[638. 475.]]
[[123. 441.]]
[[ 87. 452.]]
[[425. 286.]]
[[456. 296.]]
[[133. 400.]]
[[624. 459.]]
[[364. 285.]]
17
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[622. 421.]]
[[ 66. 472.]]
[[120. 428.]]
[[138. 414.]]
[[285. 478.]]
[[ 10. 453.]]
[[131. 430.]]
[[123. 441.]]
[[411. 295.]]
[[340. 260.]]
[[ 82. 458.]]
[[510. 240.]]
[[390. 277.]]
[[ 96. 356.]]
17
[[148. 444.]]
[[277. 460.]]
[[267. 461.]]
[[416. 273.]]
[[446. 274.]]
[[138. 4

[[267. 461.]]
[[411. 475.]]
[[120. 428.]]
[[138. 414.]]
[[ 66. 471.]]
[[  6. 453.]]
[[136. 429.]]
[[285. 478.]]
[[ 78. 462.]]
[[123. 442.]]
[[ 98. 355.]]
[[140. 386.]]
[[154. 468.]]
[[ 76. 315.]]
[[110. 447.]]
[[112. 404.]]
[[ 87. 451.]]
[[300. 464.]]
[[306. 451.]]
[[581. 288.]]
[[117. 418.]]
[[107. 388.]]
16
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[411. 475.]]
[[ 66. 472.]]
[[138. 414.]]
[[  6. 453.]]
[[285. 478.]]
[[124. 441.]]
[[120. 427.]]
[[131. 430.]]
[[ 97. 355.]]
[[ 76. 315.]]
[[ 83. 458.]]
[[575. 301.]]
[[588. 327.]]
13
[[148. 444.]]
[[277. 460.]]
[[411. 475.]]
[[267. 461.]]
[[  7. 453.]]
[[285. 478.]]
[[138. 414.]]
[[120. 428.]]
[[132. 431.]]
[[ 97. 353.]]
[[123. 442.]]
[[ 66. 472.]]
[[277. 471.]]
13
[[148. 444.]]
[[277. 460.]]
[[411. 475.]]
[[267. 461.]]
[[  7. 453.]]
[[285. 478.]]
[[138. 414.]]
[[120. 428.]]
[[132. 431.]]
[[ 97. 353.]]
[[123. 442.]]
[[ 66. 472.]]
[[277. 471.]]
17
[[148. 444.]]
[[277. 461.]]
[[267. 461.]]
[[138. 414.]]
[[411. 475.]]
[[  7. 453.]]
[[438. 2

[[277. 461.]]
[[478. 231.]]
[[484. 220.]]
[[404. 187.]]
[[488. 237.]]
[[451. 216.]]
[[267. 461.]]
[[425. 215.]]
[[441. 210.]]
[[462. 236.]]
[[120. 428.]]
[[358. 217.]]
[[401. 174.]]
[[  6. 453.]]
[[510. 246.]]
[[411. 475.]]
[[536. 249.]]
[[435. 260.]]
[[538. 280.]]
[[ 66. 471.]]
[[123. 442.]]
[[285. 478.]]
[[376. 172.]]
[[529. 266.]]
[[518. 179.]]
[[139. 418.]]
[[413. 194.]]
[[ 76. 315.]]
[[ 79. 464.]]
[[ 98. 355.]]
[[492. 277.]]
[[136. 429.]]
[[638. 221.]]
[[ 97. 413.]]
