In [1]:
import numpy as np
import cv2 as cv

def process(image, opt=1):
    # Detecting corners
    gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    corners = cv.goodFeaturesToTrack(gray, 13, 0.05, 10)#返回角点的坐标信息
    print(len(corners))
    print(corners)
    for pt in corners:
        b = np.random.randint(0, 256)
        g = np.random.randint(0, 256)
        r = np.random.randint(0, 256)
        x = np.int32(pt[0][0])
        y = np.int32(pt[0][1])
        cv.circle(image, (x, y), 5, (int(b), int(g), int(r)), 2)
    # output
    return image

file=r'C:\Users\luo yong chen\Pictures\qiqiaoban1.jpg'
src= cv.imread(file)
cv.imshow("input", src)
result = process(src)
cv.imshow('result', result)
cv.waitKey(0)
cv.destroyAllWindows()

13
[[[186. 184.]]

 [[ 92.  91.]]

 [[358. 146.]]

 [[  2.   3.]]

 [[359. 410.]]

 [[543. 594.]]

 [[282. 595.]]

 [[  2. 182.]]

 [[ 92. 279.]]

 [[225. 147.]]

 [[543. 336.]]

 [[227. 279.]]

 [[359. 518.]]]
