In [1]:
import numpy as np
import cv2 as cv

def process(image):
    # Detecting corners
    gray = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    corners = cv.goodFeaturesToTrack(gray, 100, 0.05, 10)
    print(len(corners))
    for pt in corners:
        print(pt)
        b = np.random.randint(0, 256)
        g = np.random.randint(0, 256)
        r = np.random.randint(0, 256)
        x = np.int32(pt[0][0])
        y = np.int32(pt[0][1])
        cv.circle(image, (x, y), 5, (int(b), int(g), int(r)), 2)

    # detect sub-pixel
    winSize = (5, 5)
    zeroZone = (-1, -1)
    criteria = (cv.TERM_CRITERIA_EPS + cv.TermCriteria_COUNT, 40, 0.001)
    # Calculate the refined corner locations
    corners = cv.cornerSubPix(gray, corners, winSize, zeroZone, criteria)
    # display
    for i in range(corners.shape[0]):
        print(" -- Refined Corner [", i, "]  (", corners[i, 0, 0], ",", corners[i, 0, 1], ")")
    return image

file=r'C:\Users\luo yong chen\Pictures\vtest.avi'
cap= cv.VideoCapture(file)
while True:
    ret, frame = cap.read()
    frame = cv.flip(frame, 1)
    cv.imshow('input', frame)
    result = process(frame)
    cv.imshow('result', result)
    k = cv.waitKey(50)&0xff
    if k == 27:
        break
cap.release()
cv.destroyAllWindows()

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[445. 326.]]
[[167.  70.]]
[[80. 68.]]
[[664. 520.]]
[[114.  83.]]
[[107.  57.]]
[[466.   3.]]
[[499. 276.]]
[[97. 68.]]
[[52. 66.]]
[[ 23. 175.]]
[[171.  50.]]
[[46. 78.]]
[[154. 109.]]
[[664. 510.]]
[[ 3. 52.]]
[[512. 268.]]
[[417. 461.]]
[[253. 162.]]
[[343. 178.]]
[[91. 57.]]
[[143.  34.]]
[[260. 352.]]
[[697. 518.]]
[[143.  71.]]
[[102. 299.]]
[[433. 452.]]
[[442. 460.]]
[[609. 506.]]
[[463.  66.]]
[[262. 190.]]
[[153.  64.]]
[[64. 89.]]
[[681.  53.]]
[[567.  72.]]
[[326. 185.]]
[[260. 378.]]
[[241. 172.]]
[[461.  44.]]
[[153.  36.]]
[[108.  67.]]
[[488.  18.]]
[[441.  34.]]
[[ 60. 239.]]
[[505. 230.]]
[[101.  45.]]
[[ 93. 289.]]
[[169.  38.]]
[[635. 498.]]
[[321. 120.]]
[[171.  91.]]
[[511. 135.]]
[[54. 54.]]
[[354. 203.]]
[[728.  60.]]
[[313. 197.]]
[[127. 315.]]
[[195.  37.]]
[[170. 106.]]
[[238. 186.]]
[[80. 57.]]
[[168. 132.]]
[[32. 74.]]
[[744. 442.]]
[[498.  18.]]
[[67. 43.]]
[[240. 199.]]
[[ 11. 287.]]
[[327. 160.]]
[[155.  75.]

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[167.  70.]]
[[445. 326.]]
[[80. 68.]]
[[114.  83.]]
[[664. 520.]]
[[265. 191.]]
[[488. 275.]]
[[107.  57.]]
[[466.   3.]]
[[52. 66.]]
[[97. 68.]]
[[46. 78.]]
[[171.  50.]]
[[ 23. 175.]]
[[154. 108.]]
[[417. 463.]]
[[91. 57.]]
[[ 3. 52.]]
[[143.  71.]]
[[343. 178.]]
[[664. 510.]]
[[266. 350.]]
[[697. 518.]]
[[432. 452.]]
[[143.  34.]]
[[442. 460.]]
[[118. 301.]]
[[258. 164.]]
[[241. 199.]]
[[463.  66.]]
[[115.  73.]]
[[421. 452.]]
[[610. 506.]]
[[64. 89.]]
[[499. 269.]]
[[153.  64.]]
[[567.  72.]]
[[488.  18.]]
[[461.  44.]]
[[260. 378.]]
[[153.  36.]]
[[441.  34.]]
[[681.  53.]]
[[326. 185.]]
[[ 60. 239.]]
[[492. 230.]]
[[101.  45.]]
[[319. 120.]]
[[165.  39.]]
[[243. 182.]]
[[54. 51.]]
[[314. 195.]]
[[118. 247.]]
[[728.  60.]]
[[32. 74.]]
[[171.  91.]]
[[511. 135.]]
[[632. 499.]]
[[354. 203.]]
[[ 20. 164.]]
[[80. 57.]]
[[462. 294.]]
[[327. 160.]]
[[472. 199.]]
[[ 11. 287.]]
[[745. 442.]]
[[170. 106.]]
[[483. 221.]]
[[478. 252.]]
[[259. 234

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[80. 68.]]
[[664. 520.]]
[[107.  57.]]
[[52. 66.]]
[[46. 78.]]
[[171.  50.]]
[[466.   3.]]
[[97. 68.]]
[[ 23. 175.]]
[[483. 257.]]
[[417. 463.]]
[[141. 296.]]
[[160. 109.]]
[[143.  71.]]
[[266. 350.]]
[[ 3. 52.]]
[[664. 510.]]
[[91. 57.]]
[[343. 178.]]
[[697. 518.]]
[[143.  34.]]
[[432. 452.]]
[[150. 257.]]
[[265. 166.]]
[[442. 460.]]
[[463.  66.]]
[[272. 179.]]
[[610. 506.]]
[[421. 452.]]
[[63. 89.]]
[[260. 378.]]
[[153.  64.]]
[[681.  53.]]
[[567.  72.]]
[[153.  36.]]
[[461.  44.]]
[[488.  18.]]
[[455. 261.]]
[[441.  34.]]
[[271. 203.]]
[[108.  67.]]
[[472. 198.]]
[[ 60. 239.]]
[[326. 185.]]
[[101.  45.]]
[[321. 120.]]
[[141. 248.]]
[[54. 51.]]
[[314. 195.]]
[[728.  60.]]
[[165.  39.]]
[[171.  91.]]
[[632. 499.]]
[[32. 74.]]
[[248. 186.]]
[[511. 135.]]
[[464. 220.]]
[[195.  37.]]
[[168. 132.]]
[[354. 203.]]
[[472. 269.]]
[[ 11. 287.]]
[[129. 293.]]
[[327. 160.]]
[[339. 244.]]
[[744. 442.]]
[[155.  

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[477. 256.]]
[[52. 66.]]
[[171.  50.]]
[[107.  57.]]
[[46. 78.]]
[[466.   3.]]
[[97. 68.]]
[[ 23. 175.]]
[[449. 255.]]
[[266. 350.]]
[[417. 461.]]
[[91. 57.]]
[[154. 109.]]
[[ 3. 52.]]
[[143.  71.]]
[[664. 510.]]
[[343. 178.]]
[[432. 452.]]
[[143.  34.]]
[[697. 518.]]
[[442. 460.]]
[[463.  66.]]
[[272. 169.]]
[[454. 266.]]
[[458. 281.]]
[[115.  73.]]
[[610. 506.]]
[[278. 181.]]
[[63. 89.]]
[[260. 378.]]
[[461.  44.]]
[[153.  64.]]
[[567.  72.]]
[[153.  36.]]
[[681.  53.]]
[[488.  18.]]
[[441.  34.]]
[[260. 231.]]
[[168. 256.]]
[[321. 120.]]
[[ 60. 239.]]
[[101.  45.]]
[[326. 185.]]
[[456. 219.]]
[[171.  91.]]
[[165.  39.]]
[[54. 51.]]
[[163. 301.]]
[[32. 74.]]
[[632. 499.]]
[[170. 292.]]
[[314. 195.]]
[[511. 135.]]
[[728.  60.]]
[[153. 299.]]
[[195.  37.]]
[[254. 188.]]
[[278. 194.]]
[[185. 148.]]
[[168. 132.]]
[[354. 203.]]
[[ 11. 287.]]
[[327. 160.]]
[[155.  75.]]
[[473. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[107.  57.]]
[[171.  50.]]
[[466.   3.]]
[[52. 66.]]
[[46. 78.]]
[[97. 68.]]
[[440. 262.]]
[[ 23. 175.]]
[[417. 461.]]
[[91. 57.]]
[[178. 296.]]
[[154. 109.]]
[[664. 510.]]
[[143.  71.]]
[[287. 207.]]
[[143.  34.]]
[[266. 350.]]
[[ 3. 52.]]
[[432. 452.]]
[[185. 254.]]
[[697. 518.]]
[[449. 218.]]
[[343. 178.]]
[[442. 460.]]
[[462. 259.]]
[[451. 286.]]
[[463.  66.]]
[[115.  73.]]
[[610. 506.]]
[[279. 169.]]
[[260. 378.]]
[[63. 89.]]
[[567.  72.]]
[[153.  64.]]
[[153.  36.]]
[[681.  53.]]
[[472. 198.]]
[[461.  44.]]
[[488.  18.]]
[[441.  34.]]
[[ 60. 239.]]
[[321. 120.]]
[[326. 185.]]
[[101.  45.]]
[[168. 132.]]
[[171.  91.]]
[[165.  39.]]
[[54. 51.]]
[[632. 499.]]
[[32. 74.]]
[[288. 197.]]
[[314. 195.]]
[[511. 135.]]
[[728.  60.]]
[[262. 189.]]
[[ 11. 287.]]
[[195.  37.]]
[[327. 160.]]
[[354. 203.]]
[[185. 148.]]
[[286. 182.]]
[[155.  75.]]
[[601. 201.]]
[[744. 442.]]
[[ 20. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[167.  70.]]
[[445. 326.]]
[[212. 254.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[436. 262.]]
[[466.   3.]]
[[52. 66.]]
[[46. 78.]]
[[171.  50.]]
[[107.  57.]]
[[97. 68.]]
[[ 23. 175.]]
[[417. 461.]]
[[91. 57.]]
[[154. 109.]]
[[260. 352.]]
[[143.  71.]]
[[664. 510.]]
[[432. 452.]]
[[ 3. 52.]]
[[143.  34.]]
[[697. 518.]]
[[343. 178.]]
[[294. 200.]]
[[435. 214.]]
[[442. 460.]]
[[269. 193.]]
[[204. 304.]]
[[463.  66.]]
[[610. 506.]]
[[115.  73.]]
[[ 16. 400.]]
[[63. 89.]]
[[567.  72.]]
[[260. 378.]]
[[153.  64.]]
[[153.  36.]]
[[461.  44.]]
[[488.  18.]]
[[681.  53.]]
[[292. 173.]]
[[  6. 366.]]
[[441.  34.]]
[[213. 293.]]
[[326. 185.]]
[[195. 290.]]
[[ 60. 239.]]
[[101.  45.]]
[[319. 120.]]
[[314. 195.]]
[[165.  39.]]
[[54. 51.]]
[[632. 499.]]
[[171.  91.]]
[[511. 135.]]
[[728.  60.]]
[[32. 74.]]
[[354. 203.]]
[[195.  37.]]
[[ 11. 287.]]
[[327. 160.]]
[[601. 201.]]
[[744. 442.]]
[[ 14. 383.]]
[[ 20. 164.]]
[[155.  75.]]
[[498.  18.]]
[[284. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[ 19. 356.]]
[[222. 299.]]
[[167.  70.]]
[[  3. 394.]]
[[445. 326.]]
[[228. 254.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[52. 66.]]
[[466.   3.]]
[[97. 68.]]
[[171.  50.]]
[[107.  57.]]
[[46. 78.]]
[[ 23. 175.]]
[[436. 251.]]
[[424. 260.]]
[[160. 109.]]
[[417. 463.]]
[[91. 57.]]
[[266. 350.]]
[[664. 510.]]
[[432. 452.]]
[[143.  71.]]
[[ 3. 52.]]
[[143.  34.]]
[[697. 518.]]
[[343. 178.]]
[[442. 460.]]
[[ 14. 405.]]
[[463.  66.]]
[[209. 290.]]
[[115.  73.]]
[[610. 506.]]
[[260. 378.]]
[[296. 173.]]
[[567.  72.]]
[[63. 89.]]
[[421. 452.]]
[[153.  64.]]
[[488.  18.]]
[[461.  44.]]
[[153.  36.]]
[[422. 212.]]
[[681.  53.]]
[[282. 212.]]
[[472. 198.]]
[[441.  34.]]
[[326. 185.]]
[[ 60. 239.]]
[[101.  45.]]
[[319. 120.]]
[[314. 195.]]
[[54. 51.]]
[[632. 499.]]
[[728.  60.]]
[[511. 135.]]
[[171.  91.]]
[[ 17. 368.]]
[[32. 74.]]
[[165.  39.]]
[[195.  37.]]
[[354. 203.]]
[[302. 211.]]
[[440. 289.]]
[[327. 160.]]
[[ 11. 287.]]
[[155.  75.]]
[[297. 2

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[254. 252.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[ 16. 403.]]
[[80. 68.]]
[[664. 520.]]
[[52. 66.]]
[[107.  57.]]
[[466.   3.]]
[[171.  50.]]
[[97. 68.]]
[[46. 78.]]
[[399. 246.]]
[[ 23. 175.]]
[[ 43. 348.]]
[[417. 463.]]
[[154. 109.]]
[[260. 352.]]
[[143.  71.]]
[[427. 244.]]
[[91. 57.]]
[[664. 510.]]
[[343. 178.]]
[[ 3. 52.]]
[[697. 518.]]
[[432. 452.]]
[[143.  34.]]
[[312. 199.]]
[[442. 460.]]
[[463.  66.]]
[[309. 176.]]
[[115.  73.]]
[[260. 378.]]
[[610. 506.]]
[[63. 89.]]
[[421. 452.]]
[[245. 309.]]
[[461.  44.]]
[[567.  72.]]
[[488.  18.]]
[[153.  64.]]
[[153.  36.]]
[[410. 273.]]
[[681.  53.]]
[[441.  34.]]
[[300. 183.]]
[[ 60. 239.]]
[[238. 287.]]
[[295. 241.]]
[[321. 120.]]
[[101.  45.]]
[[326. 185.]]
[[408. 207.]]
[[32. 74.]]
[[54. 51.]]
[[165.  39.]]
[[632. 499.]]
[[171.  91.]]
[[511. 135.]]
[[728.  60.]]
[[354. 203.]]
[[195.  37.]]
[[155.  75.]]
[[170. 106.]]
[[ 20. 164.]]
[[254. 290.]]
[[ 11. 287.]]
[[687.  26.]]
[[327. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[ 40. 342.]]
[[167.  70.]]
[[445. 326.]]
[[269. 252.]]
[[114.  83.]]
[[261. 292.]]
[[664. 520.]]
[[80. 68.]]
[[466.   3.]]
[[52. 66.]]
[[107.  57.]]
[[171.  50.]]
[[46. 78.]]
[[97. 68.]]
[[ 36. 353.]]
[[ 28. 381.]]
[[ 23. 175.]]
[[417. 461.]]
[[ 3. 52.]]
[[143.  71.]]
[[91. 57.]]
[[154. 109.]]
[[266. 350.]]
[[432. 452.]]
[[664. 510.]]
[[396. 246.]]
[[343. 178.]]
[[697. 518.]]
[[321. 184.]]
[[442. 460.]]
[[143.  34.]]
[[463.  66.]]
[[115.  73.]]
[[403. 268.]]
[[610. 506.]]
[[249. 285.]]
[[ 45. 359.]]
[[63. 89.]]
[[461.  44.]]
[[260. 378.]]
[[153.  64.]]
[[567.  72.]]
[[153.  36.]]
[[488.  18.]]
[[681.  53.]]
[[420. 242.]]
[[ 60. 239.]]
[[441.  34.]]
[[101.  45.]]
[[321. 120.]]
[[165.  39.]]
[[632. 499.]]
[[54. 51.]]
[[511. 135.]]
[[171.  91.]]
[[354. 203.]]
[[195.  37.]]
[[728.  60.]]
[[472. 198.]]
[[32. 74.]]
[[260. 244.]]
[[309. 185.]]
[[170. 106.]]
[[155.  75.]]
[[327. 160.]]
[[ 20. 164.]]
[[601. 201.]]
[[744. 442.]]
[[80. 57.]]
[[498.  18

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[ 50. 340.]]
[[167.  70.]]
[[445. 326.]]
[[296. 251.]]
[[ 32. 387.]]
[[664. 520.]]
[[114.  83.]]
[[335. 201.]]
[[80. 68.]]
[[52. 66.]]
[[466.   3.]]
[[107.  57.]]
[[171.  50.]]
[[387. 224.]]
[[46. 78.]]
[[97. 68.]]
[[ 23. 175.]]
[[277. 284.]]
[[417. 463.]]
[[154. 109.]]
[[143.  71.]]
[[343. 178.]]
[[260. 352.]]
[[91. 57.]]
[[697. 518.]]
[[664. 510.]]
[[ 3. 52.]]
[[432. 452.]]
[[  6. 291.]]
[[ 69. 373.]]
[[331. 182.]]
[[442. 460.]]
[[143.  34.]]
[[395. 250.]]
[[115.  73.]]
[[463.  66.]]
[[ 62. 358.]]
[[407. 240.]]
[[610. 506.]]
[[325. 204.]]
[[341. 244.]]
[[421. 452.]]
[[373. 224.]]
[[63. 89.]]
[[285. 300.]]
[[461.  44.]]
[[260. 378.]]
[[567.  72.]]
[[153.  64.]]
[[681.  53.]]
[[153.  36.]]
[[320. 213.]]
[[488.  18.]]
[[ 30. 331.]]
[[ 18. 347.]]
[[441.  34.]]
[[ 60. 239.]]
[[ 50. 355.]]
[[101.  45.]]
[[321. 120.]]
[[54. 51.]]
[[632. 499.]]
[[165.  39.]]
[[511. 135.]]
[[313. 197.]]
[[171.  91.]]
[[728.  60.]]
[[32. 74.]]
[[354. 203.]]
[[195.  

100
[[74. 83.]]
[[371.  34.]]
[[ 73. 329.]]
[[629. 510.]]
[[ 52. 365.]]
[[167.  70.]]
[[445. 326.]]
[[318. 250.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[52. 66.]]
[[107.  57.]]
[[466.   3.]]
[[46. 78.]]
[[171.  50.]]
[[97. 68.]]
[[300. 285.]]
[[378. 223.]]
[[ 22. 176.]]
[[417. 463.]]
[[311. 293.]]
[[154. 109.]]
[[91. 57.]]
[[266. 350.]]
[[143.  71.]]
[[664. 510.]]
[[432. 452.]]
[[389. 246.]]
[[ 3. 52.]]
[[697. 518.]]
[[143.  34.]]
[[442. 460.]]
[[400. 238.]]
[[342. 201.]]
[[463.  66.]]
[[ 70. 339.]]
[[ 29. 338.]]
[[346. 182.]]
[[115.  73.]]
[[610. 506.]]
[[ 67. 373.]]
[[421. 452.]]
[[378. 239.]]
[[63. 89.]]
[[567.  72.]]
[[461.  44.]]
[[260. 378.]]
[[681.  53.]]
[[488.  18.]]
[[153.  36.]]
[[153.  64.]]
[[ 32. 173.]]
[[340. 244.]]
[[441.  34.]]
[[ 60. 239.]]
[[321. 120.]]
[[101.  45.]]
[[353. 203.]]
[[326. 185.]]
[[632. 499.]]
[[165.  39.]]
[[ 11. 287.]]
[[54. 51.]]
[[313. 197.]]
[[32. 74.]]
[[511. 135.]]
[[728.  60.]]
[[195.  37.]]
[[171.  91.]]
[[170. 106.]]
[[328. 159.]]
[[ 20. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[167.  70.]]
[[353. 203.]]
[[445. 326.]]
[[114.  83.]]
[[399. 233.]]
[[ 85. 324.]]
[[664. 520.]]
[[80. 68.]]
[[52. 66.]]
[[466.   3.]]
[[107.  57.]]
[[46. 78.]]
[[171.  50.]]
[[97. 68.]]
[[330. 244.]]
[[ 22. 176.]]
[[417. 463.]]
[[91. 57.]]
[[266. 350.]]
[[143.  71.]]
[[160. 109.]]
[[664. 510.]]
[[143.  34.]]
[[697. 518.]]
[[370. 236.]]
[[ 3. 52.]]
[[432. 452.]]
[[343. 178.]]
[[442. 460.]]
[[ 67. 374.]]
[[463.  66.]]
[[346. 190.]]
[[315. 281.]]
[[349. 243.]]
[[115.  73.]]
[[609. 506.]]
[[359. 191.]]
[[63. 89.]]
[[461.  44.]]
[[567.  72.]]
[[260. 378.]]
[[681.  53.]]
[[ 86. 353.]]
[[365. 210.]]
[[153.  36.]]
[[421. 452.]]
[[488.  18.]]
[[153.  64.]]
[[ 32. 173.]]
[[358. 178.]]
[[384. 247.]]
[[441.  34.]]
[[326. 185.]]
[[ 60. 239.]]
[[321. 120.]]
[[101.  45.]]
[[322. 229.]]
[[54. 51.]]
[[632. 499.]]
[[728.  60.]]
[[32. 74.]]
[[314. 195.]]
[[165.  39.]]
[[511. 135.]]
[[378. 195.]]
[[170.  91.]]
[[327. 160.]]
[[195.  37.]]
[[ 11. 287.]]
[[170. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[ 95. 317.]]
[[ 78. 361.]]
[[167.  70.]]
[[335. 244.]]
[[445. 326.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[466.   3.]]
[[46. 78.]]
[[107.  57.]]
[[52. 66.]]
[[ 91. 328.]]
[[171.  50.]]
[[325. 244.]]
[[97. 68.]]
[[ 23. 175.]]
[[355. 219.]]
[[160. 109.]]
[[417. 463.]]
[[266. 350.]]
[[91. 57.]]
[[664. 510.]]
[[143.  71.]]
[[ 3. 52.]]
[[372. 237.]]
[[143.  34.]]
[[343. 178.]]
[[697. 518.]]
[[393. 230.]]
[[432. 452.]]
[[442. 460.]]
[[354. 203.]]
[[352. 241.]]
[[463.  66.]]
[[115.  73.]]
[[ 67. 324.]]
[[609. 506.]]
[[260. 378.]]
[[370. 188.]]
[[63. 89.]]
[[153.  64.]]
[[567.  72.]]
[[421. 452.]]
[[681.  53.]]
[[461.  44.]]
[[153.  36.]]
[[488.  18.]]
[[441.  34.]]
[[ 60. 239.]]
[[ 95. 359.]]
[[321. 120.]]
[[101.  45.]]
[[326. 185.]]
[[54. 51.]]
[[32. 74.]]
[[632. 499.]]
[[171.  91.]]
[[314. 195.]]
[[165.  39.]]
[[ 41. 352.]]
[[728.  60.]]
[[511. 135.]]
[[374. 251.]]
[[195.  37.]]
[[326. 276.]]
[[321. 305.]]
[[327. 160.]]
[[ 11. 287.]]
[[744. 4

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[ 99. 315.]]
[[354. 237.]]
[[334. 244.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[46. 78.]]
[[107.  57.]]
[[52. 66.]]
[[466.   3.]]
[[171.  50.]]
[[97. 68.]]
[[333. 257.]]
[[260. 352.]]
[[417. 463.]]
[[160. 109.]]
[[ 23. 175.]]
[[91. 57.]]
[[143.  71.]]
[[664. 510.]]
[[ 3. 52.]]
[[143.  34.]]
[[697. 518.]]
[[343. 178.]]
[[102. 331.]]
[[432. 452.]]
[[442. 460.]]
[[357. 191.]]
[[463.  66.]]
[[353. 203.]]
[[609. 506.]]
[[260. 378.]]
[[109. 358.]]
[[63. 89.]]
[[421. 452.]]
[[567.  72.]]
[[153.  64.]]
[[387. 232.]]
[[372. 181.]]
[[461.  44.]]
[[ 81. 308.]]
[[681.  53.]]
[[153.  36.]]
[[488.  18.]]
[[441.  34.]]
[[370. 249.]]
[[ 44. 309.]]
[[ 60. 239.]]
[[ 69. 324.]]
[[101.  45.]]
[[321. 120.]]
[[108.  67.]]
[[326. 185.]]
[[632. 499.]]
[[382. 195.]]
[[54. 51.]]
[[728.  60.]]
[[165.  39.]]
[[32. 74.]]
[[171.  91.]]
[[314. 195.]]
[[340. 296.]]
[[511. 135.]]
[[195.  37.]]
[[ 92. 360.]]
[[327. 160.]]
[[355. 271.]]
[[ 11. 2

100
[[371.  34.]]
[[74. 83.]]
[[629. 510.]]
[[117. 311.]]
[[167.  70.]]
[[354. 232.]]
[[445. 326.]]
[[114.  83.]]
[[115. 325.]]
[[340. 244.]]
[[664. 520.]]
[[80. 68.]]
[[ 93. 349.]]
[[52. 66.]]
[[466.   3.]]
[[107.  57.]]
[[46. 78.]]
[[171.  50.]]
[[97. 68.]]
[[417. 463.]]
[[ 23. 175.]]
[[91. 57.]]
[[160. 109.]]
[[266. 350.]]
[[143.  71.]]
[[664. 510.]]
[[143.  34.]]
[[697. 518.]]
[[124. 350.]]
[[ 3. 52.]]
[[343. 178.]]
[[432. 452.]]
[[442. 460.]]
[[360. 221.]]
[[463.  66.]]
[[115.  73.]]
[[609. 506.]]
[[260. 378.]]
[[63. 89.]]
[[567.  72.]]
[[421. 452.]]
[[153.  64.]]
[[461.  44.]]
[[681.  53.]]
[[153.  36.]]
[[359. 192.]]
[[488.  18.]]
[[441.  34.]]
[[ 60. 239.]]
[[ 87. 316.]]
[[376. 244.]]
[[321. 120.]]
[[377. 183.]]
[[171.  91.]]
[[101.  45.]]
[[326. 185.]]
[[632. 499.]]
[[54. 51.]]
[[186. 147.]]
[[728.  60.]]
[[314. 195.]]
[[511. 135.]]
[[32. 74.]]
[[195.  37.]]
[[165.  39.]]
[[354. 203.]]
[[360. 268.]]
[[327. 160.]]
[[ 11. 287.]]
[[80. 57.]]
[[386. 230.]]
[[387. 219.]]
[[744. 442

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[131. 303.]]
[[167.  70.]]
[[445. 326.]]
[[352. 241.]]
[[114.  83.]]
[[340. 244.]]
[[355. 227.]]
[[664. 520.]]
[[80. 68.]]
[[112. 342.]]
[[97. 68.]]
[[466.   3.]]
[[107.  57.]]
[[52. 66.]]
[[46. 78.]]
[[171.  50.]]
[[124. 350.]]
[[ 23. 175.]]
[[417. 463.]]
[[160. 109.]]
[[266. 350.]]
[[91. 57.]]
[[143.  71.]]
[[143.  34.]]
[[664. 510.]]
[[697. 518.]]
[[364. 221.]]
[[ 3. 52.]]
[[432. 452.]]
[[343. 178.]]
[[442. 460.]]
[[114.  73.]]
[[463.  66.]]
[[609. 506.]]
[[260. 378.]]
[[63. 89.]]
[[421. 452.]]
[[681.  53.]]
[[153.  64.]]
[[ 84. 311.]]
[[373. 234.]]
[[461.  44.]]
[[567.  72.]]
[[153.  36.]]
[[326. 185.]]
[[488.  18.]]
[[128. 313.]]
[[ 60. 239.]]
[[441.  34.]]
[[361. 292.]]
[[360. 192.]]
[[186. 147.]]
[[321. 120.]]
[[101.  45.]]
[[54. 51.]]
[[632. 499.]]
[[171.  91.]]
[[382. 257.]]
[[511. 135.]]
[[354. 203.]]
[[32. 74.]]
[[361. 262.]]
[[370. 252.]]
[[314. 195.]]
[[165.  39.]]
[[ 11. 287.]]
[[728.  60.]]
[[195.  37.]]
[[369. 186.]]
[[327. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[355. 224.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[340. 244.]]
[[352. 241.]]
[[664. 520.]]
[[80. 68.]]
[[466.   3.]]
[[107.  57.]]
[[52. 66.]]
[[46. 78.]]
[[97. 68.]]
[[171.  50.]]
[[91. 57.]]
[[417. 463.]]
[[ 23. 175.]]
[[154. 108.]]
[[260. 352.]]
[[664. 510.]]
[[343. 178.]]
[[143.  71.]]
[[432. 452.]]
[[125. 348.]]
[[143.  34.]]
[[697. 518.]]
[[150. 299.]]
[[ 3. 52.]]
[[442. 460.]]
[[381. 227.]]
[[115.  73.]]
[[463.  66.]]
[[609. 506.]]
[[387. 195.]]
[[63. 89.]]
[[421. 452.]]
[[260. 378.]]
[[153.  64.]]
[[461.  44.]]
[[567.  72.]]
[[326. 185.]]
[[681.  53.]]
[[488.  18.]]
[[106. 309.]]
[[153.  36.]]
[[441.  34.]]
[[ 60. 239.]]
[[141. 338.]]
[[363. 191.]]
[[358. 258.]]
[[321. 120.]]
[[101.  45.]]
[[54. 51.]]
[[171.  91.]]
[[632. 499.]]
[[380. 259.]]
[[ 86. 338.]]
[[511. 135.]]
[[728.  60.]]
[[ 90. 303.]]
[[32. 74.]]
[[313. 197.]]
[[165.  39.]]
[[354. 203.]]
[[185. 147.]]
[[195.  37.]]
[[170. 106.]]
[[327. 160.]]
[[ 11. 287.]]
[[744. 4

100
[[371. 228.]]
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[153. 293.]]
[[355. 219.]]
[[167.  70.]]
[[445. 326.]]
[[340. 244.]]
[[114.  83.]]
[[357. 240.]]
[[664. 520.]]
[[80. 68.]]
[[466.   3.]]
[[107.  57.]]
[[137. 338.]]
[[97. 68.]]
[[52. 66.]]
[[171.  50.]]
[[46. 78.]]
[[363. 191.]]
[[260. 352.]]
[[417. 463.]]
[[91. 57.]]
[[ 23. 175.]]
[[154. 108.]]
[[143.  71.]]
[[664. 510.]]
[[143.  34.]]
[[343. 178.]]
[[697. 518.]]
[[ 3. 52.]]
[[383. 226.]]
[[442. 460.]]
[[432. 452.]]
[[115.  73.]]
[[609. 506.]]
[[463.  66.]]
[[260. 378.]]
[[125. 303.]]
[[63. 89.]]
[[390. 194.]]
[[422. 453.]]
[[681.  53.]]
[[153.  64.]]
[[326. 185.]]
[[461.  44.]]
[[567.  72.]]
[[348. 276.]]
[[373. 182.]]
[[488.  18.]]
[[441.  34.]]
[[153.  36.]]
[[ 60. 239.]]
[[354. 203.]]
[[111. 304.]]
[[321. 120.]]
[[171.  91.]]
[[314. 195.]]
[[101.  45.]]
[[728.  60.]]
[[54. 51.]]
[[632. 499.]]
[[511. 135.]]
[[195.  37.]]
[[32. 74.]]
[[327. 160.]]
[[366. 255.]]
[[165.  39.]]
[[170. 106.]]
[[ 11. 287.]]
[[744. 442.]]
[[ 20. 1

100
[[367. 228.]]
[[74. 83.]]
[[371.  34.]]
[[160. 294.]]
[[629. 510.]]
[[379. 222.]]
[[328. 244.]]
[[167.  70.]]
[[445. 326.]]
[[141. 338.]]
[[340. 244.]]
[[114.  83.]]
[[375. 193.]]
[[80. 68.]]
[[664. 520.]]
[[466.   3.]]
[[107.  57.]]
[[46. 78.]]
[[52. 66.]]
[[97. 68.]]
[[171.  50.]]
[[91. 57.]]
[[ 23. 175.]]
[[361. 191.]]
[[417. 463.]]
[[143.  71.]]
[[664. 510.]]
[[266. 350.]]
[[154. 108.]]
[[152. 304.]]
[[143.  34.]]
[[343. 178.]]
[[697. 518.]]
[[432. 452.]]
[[442. 460.]]
[[ 3. 52.]]
[[139. 290.]]
[[353. 203.]]
[[463.  66.]]
[[115.  73.]]
[[610. 506.]]
[[260. 378.]]
[[354. 226.]]
[[357. 255.]]
[[165. 308.]]
[[171. 329.]]
[[63. 89.]]
[[422. 453.]]
[[681.  53.]]
[[153.  64.]]
[[472. 198.]]
[[326. 185.]]
[[461.  44.]]
[[382. 185.]]
[[567.  72.]]
[[118. 272.]]
[[488.  18.]]
[[153.  36.]]
[[351. 280.]]
[[441.  34.]]
[[ 60. 239.]]
[[314. 195.]]
[[321. 120.]]
[[171.  91.]]
[[101.  45.]]
[[54. 51.]]
[[632. 499.]]
[[511. 135.]]
[[195.  37.]]
[[728.  60.]]
[[165.  39.]]
[[32. 74.]]
[[327. 1

100
[[74. 83.]]
[[371.  34.]]
[[374. 221.]]
[[629. 510.]]
[[172. 289.]]
[[364. 229.]]
[[334. 244.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[148. 328.]]
[[52. 66.]]
[[80. 68.]]
[[664. 520.]]
[[375. 192.]]
[[107.  57.]]
[[46. 78.]]
[[466.   3.]]
[[171.  50.]]
[[97. 68.]]
[[323. 244.]]
[[91. 57.]]
[[417. 463.]]
[[ 23. 175.]]
[[143.  71.]]
[[266. 350.]]
[[664. 510.]]
[[154. 109.]]
[[356. 250.]]
[[143.  34.]]
[[171. 329.]]
[[173. 302.]]
[[ 3. 52.]]
[[697. 518.]]
[[343. 178.]]
[[432. 452.]]
[[361. 192.]]
[[442. 460.]]
[[325. 201.]]
[[354. 203.]]
[[150. 284.]]
[[463.  66.]]
[[609. 506.]]
[[260. 378.]]
[[140. 296.]]
[[115.  73.]]
[[421. 452.]]
[[326. 185.]]
[[63. 89.]]
[[681.  53.]]
[[461.  44.]]
[[567.  72.]]
[[153.  64.]]
[[375. 209.]]
[[384. 184.]]
[[153.  36.]]
[[488.  18.]]
[[333. 266.]]
[[441.  34.]]
[[ 60. 239.]]
[[314. 195.]]
[[322. 213.]]
[[367. 184.]]
[[321. 120.]]
[[171.  91.]]
[[101.  45.]]
[[632. 499.]]
[[54. 51.]]
[[728.  60.]]
[[511. 135.]]
[[32. 74.]]
[[165.  39.]]
[[195.  

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[354. 227.]]
[[167.  70.]]
[[445. 326.]]
[[353. 203.]]
[[114.  83.]]
[[352. 241.]]
[[197. 284.]]
[[80. 68.]]
[[466.   3.]]
[[664. 520.]]
[[52. 66.]]
[[107.  57.]]
[[373. 192.]]
[[367. 215.]]
[[46. 78.]]
[[97. 68.]]
[[171.  50.]]
[[362. 186.]]
[[91. 57.]]
[[417. 463.]]
[[ 23. 175.]]
[[664. 510.]]
[[266. 350.]]
[[154. 108.]]
[[143.  71.]]
[[343. 178.]]
[[143.  34.]]
[[697. 518.]]
[[432. 452.]]
[[ 3. 52.]]
[[171. 328.]]
[[442. 460.]]
[[463.  66.]]
[[609. 506.]]
[[260. 378.]]
[[115.  73.]]
[[421. 452.]]
[[326. 185.]]
[[392. 193.]]
[[63. 89.]]
[[382. 182.]]
[[681.  53.]]
[[461.  44.]]
[[567.  72.]]
[[153.  64.]]
[[488.  18.]]
[[441.  34.]]
[[ 60. 239.]]
[[153.  36.]]
[[148. 293.]]
[[313. 197.]]
[[180. 307.]]
[[321. 120.]]
[[171.  91.]]
[[136. 288.]]
[[101.  45.]]
[[315. 207.]]
[[632. 499.]]
[[54. 51.]]
[[165.  39.]]
[[728.  60.]]
[[32. 74.]]
[[511. 135.]]
[[165. 279.]]
[[  8. 300.]]
[[327. 160.]]
[[326. 201.]]
[[319. 259.]]
[[195.  37.]]
[[170. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[197. 279.]]
[[167.  70.]]
[[445. 326.]]
[[177. 320.]]
[[114.  83.]]
[[466.   3.]]
[[80. 68.]]
[[352. 241.]]
[[664. 520.]]
[[52. 66.]]
[[107.  57.]]
[[46. 78.]]
[[353. 203.]]
[[171.  50.]]
[[97. 68.]]
[[91. 57.]]
[[ 23. 175.]]
[[154. 109.]]
[[417. 461.]]
[[664. 510.]]
[[143.  71.]]
[[343. 178.]]
[[266. 350.]]
[[192. 289.]]
[[143.  34.]]
[[697. 518.]]
[[378. 181.]]
[[172. 286.]]
[[ 3. 52.]]
[[432. 452.]]
[[442. 460.]]
[[364. 216.]]
[[172. 275.]]
[[609. 506.]]
[[463.  66.]]
[[260. 378.]]
[[115.  73.]]
[[326. 185.]]
[[461.  44.]]
[[325. 204.]]
[[63. 89.]]
[[681.  53.]]
[[389. 194.]]
[[567.  72.]]
[[153.  64.]]
[[152. 309.]]
[[488.  18.]]
[[  8. 287.]]
[[361. 186.]]
[[441.  34.]]
[[153.  36.]]
[[ 60. 239.]]
[[171.  91.]]
[[370. 192.]]
[[ 22. 299.]]
[[101.  45.]]
[[321. 120.]]
[[632. 499.]]
[[54. 51.]]
[[728.  60.]]
[[511. 135.]]
[[165.  39.]]
[[162. 292.]]
[[148. 281.]]
[[32. 74.]]
[[374. 212.]]
[[182. 236.]]
[[ 15. 346.]]
[[196. 318.]]
[[195.  

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[354. 227.]]
[[207. 276.]]
[[167.  70.]]
[[445. 326.]]
[[351. 243.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[466.   3.]]
[[187. 268.]]
[[354. 203.]]
[[107.  57.]]
[[97. 68.]]
[[52. 66.]]
[[46. 78.]]
[[171.  50.]]
[[91. 57.]]
[[417. 463.]]
[[217. 293.]]
[[664. 510.]]
[[ 23. 175.]]
[[160. 109.]]
[[143.  71.]]
[[343. 178.]]
[[266. 350.]]
[[365. 218.]]
[[143.  34.]]
[[697. 518.]]
[[432. 452.]]
[[442. 460.]]
[[ 3. 52.]]
[[ 52. 331.]]
[[225. 312.]]
[[318. 197.]]
[[349. 190.]]
[[181. 284.]]
[[463.  66.]]
[[609. 506.]]
[[115.  73.]]
[[ 46. 323.]]
[[260. 378.]]
[[326. 185.]]
[[377. 181.]]
[[153. 270.]]
[[421. 452.]]
[[63. 89.]]
[[681.  53.]]
[[153.  64.]]
[[461.  44.]]
[[567.  72.]]
[[317. 260.]]
[[488.  18.]]
[[153.  36.]]
[[441.  34.]]
[[ 23. 334.]]
[[ 30. 274.]]
[[178. 261.]]
[[ 60. 239.]]
[[319. 232.]]
[[160. 280.]]
[[341. 243.]]
[[101.  45.]]
[[321. 120.]]
[[161. 258.]]
[[171.  91.]]
[[632. 499.]]
[[728.  60.]]
[[54. 51.]]
[[165.  39.]]
[[511.

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[221. 274.]]
[[354. 228.]]
[[167.  70.]]
[[445. 326.]]
[[351. 243.]]
[[114.  83.]]
[[466.   3.]]
[[228. 310.]]
[[80. 68.]]
[[664. 520.]]
[[353. 203.]]
[[107.  57.]]
[[46. 78.]]
[[52. 66.]]
[[171.  50.]]
[[97. 68.]]
[[218. 286.]]
[[ 61. 330.]]
[[91. 57.]]
[[417. 463.]]
[[664. 510.]]
[[160. 109.]]
[[143.  71.]]
[[348. 190.]]
[[ 23. 175.]]
[[343. 178.]]
[[266. 350.]]
[[198. 308.]]
[[371. 193.]]
[[697. 518.]]
[[143.  34.]]
[[442. 460.]]
[[ 3. 52.]]
[[432. 452.]]
[[318. 193.]]
[[463.  66.]]
[[326. 185.]]
[[115.  73.]]
[[610. 506.]]
[[361. 216.]]
[[371. 218.]]
[[260. 378.]]
[[187. 279.]]
[[308. 185.]]
[[ 55. 322.]]
[[421. 452.]]
[[191. 269.]]
[[461.  44.]]
[[63. 89.]]
[[153.  64.]]
[[681.  53.]]
[[379. 182.]]
[[162. 268.]]
[[567.  72.]]
[[488.  18.]]
[[153.  36.]]
[[389. 194.]]
[[441.  34.]]
[[359. 191.]]
[[ 60. 239.]]
[[170. 234.]]
[[369. 208.]]
[[319. 119.]]
[[101.  45.]]
[[171.  91.]]
[[632. 499.]]
[[ 41. 272.]]
[[54. 51.]]
[[728.  60.]]
[[165.

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[80. 68.]]
[[466.   3.]]
[[664. 520.]]
[[350. 243.]]
[[235. 303.]]
[[107.  57.]]
[[353. 203.]]
[[346. 190.]]
[[52. 66.]]
[[46. 78.]]
[[171.  50.]]
[[97. 68.]]
[[91. 57.]]
[[664. 510.]]
[[355. 226.]]
[[417. 463.]]
[[143.  71.]]
[[ 23. 175.]]
[[154. 109.]]
[[266. 350.]]
[[343. 178.]]
[[697. 518.]]
[[432. 452.]]
[[374. 192.]]
[[143.  34.]]
[[249. 267.]]
[[322. 223.]]
[[442. 460.]]
[[ 3. 52.]]
[[463.  66.]]
[[610. 506.]]
[[115.  73.]]
[[260. 378.]]
[[241. 261.]]
[[421. 452.]]
[[320. 186.]]
[[461.  44.]]
[[153.  64.]]
[[64. 89.]]
[[681.  53.]]
[[567.  72.]]
[[185. 276.]]
[[488.  18.]]
[[441.  34.]]
[[ 66. 277.]]
[[378. 181.]]
[[222. 309.]]
[[385. 190.]]
[[153.  36.]]
[[ 60. 239.]]
[[101.  45.]]
[[32. 74.]]
[[319. 120.]]
[[171.  91.]]
[[632. 499.]]
[[301. 250.]]
[[180. 230.]]
[[54. 51.]]
[[172. 271.]]
[[ 57. 263.]]
[[728.  60.]]
[[165.  39.]]
[[511. 135.]]
[[327. 201.]]
[[195.  37.]]
[[371. 213.]]
[[ 20. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[255. 263.]]
[[332. 188.]]
[[167.  70.]]
[[445. 326.]]
[[344. 190.]]
[[353. 203.]]
[[354. 225.]]
[[114.  83.]]
[[664. 520.]]
[[466.   3.]]
[[80. 68.]]
[[233. 304.]]
[[352. 241.]]
[[107.  57.]]
[[340. 244.]]
[[46. 78.]]
[[171.  50.]]
[[52. 66.]]
[[97. 67.]]
[[ 23. 175.]]
[[91. 57.]]
[[201. 272.]]
[[664. 510.]]
[[143.  71.]]
[[417. 461.]]
[[212. 270.]]
[[249. 300.]]
[[266. 350.]]
[[160. 109.]]
[[343. 178.]]
[[697. 518.]]
[[432. 452.]]
[[ 3. 52.]]
[[143.  34.]]
[[376. 192.]]
[[442. 460.]]
[[463.  66.]]
[[332. 201.]]
[[610. 506.]]
[[115.  73.]]
[[ 84. 277.]]
[[184. 297.]]
[[681.  53.]]
[[461.  44.]]
[[260. 378.]]
[[153.  64.]]
[[567.  72.]]
[[63. 89.]]
[[441.  34.]]
[[320. 236.]]
[[ 76. 322.]]
[[488.  18.]]
[[153.  36.]]
[[342. 201.]]
[[372. 213.]]
[[ 60. 239.]]
[[321. 120.]]
[[ 76. 261.]]
[[54. 51.]]
[[171.  91.]]
[[321. 184.]]
[[632. 499.]]
[[101.  45.]]
[[189. 267.]]
[[728.  60.]]
[[316. 221.]]
[[32. 74.]]
[[165.  39.]]
[[386. 190.]]
[[511. 1

100
[[250. 297.]]
[[74. 83.]]
[[355. 229.]]
[[371.  34.]]
[[629. 510.]]
[[346. 243.]]
[[256. 261.]]
[[353. 203.]]
[[167.  70.]]
[[255. 274.]]
[[445. 326.]]
[[335. 201.]]
[[114.  83.]]
[[80. 68.]]
[[664. 520.]]
[[107.  57.]]
[[46. 78.]]
[[466.   3.]]
[[52. 66.]]
[[171.  50.]]
[[97. 68.]]
[[344. 190.]]
[[91. 57.]]
[[143.  71.]]
[[335. 179.]]
[[102. 315.]]
[[417. 463.]]
[[160. 109.]]
[[ 23. 175.]]
[[266. 350.]]
[[664. 510.]]
[[206. 270.]]
[[377. 193.]]
[[697. 518.]]
[[432. 452.]]
[[ 3. 52.]]
[[143.  34.]]
[[369. 216.]]
[[463.  66.]]
[[442. 460.]]
[[221. 268.]]
[[115.  73.]]
[[610. 506.]]
[[323. 187.]]
[[260. 378.]]
[[421. 452.]]
[[153.  64.]]
[[461.  44.]]
[[63. 89.]]
[[488.  18.]]
[[681.  53.]]
[[441.  34.]]
[[567.  72.]]
[[ 98. 305.]]
[[153.  36.]]
[[325. 202.]]
[[347. 253.]]
[[171.  91.]]
[[314. 195.]]
[[ 60. 239.]]
[[321. 120.]]
[[ 84. 257.]]
[[54. 51.]]
[[32. 74.]]
[[101.  45.]]
[[632. 499.]]
[[728.  60.]]
[[511. 135.]]
[[165.  39.]]
[[ 95. 270.]]
[[195.  37.]]
[[327. 160.]]
[[383. 2

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[268. 260.]]
[[167.  70.]]
[[445. 326.]]
[[353. 203.]]
[[376. 192.]]
[[114.  83.]]
[[80. 68.]]
[[664. 520.]]
[[352. 241.]]
[[360. 226.]]
[[107.  57.]]
[[52. 66.]]
[[46. 78.]]
[[466.   3.]]
[[121. 302.]]
[[341. 244.]]
[[171.  50.]]
[[97. 68.]]
[[91. 57.]]
[[160. 109.]]
[[343. 180.]]
[[417. 461.]]
[[143.  71.]]
[[ 23. 175.]]
[[266. 350.]]
[[250. 298.]]
[[664. 510.]]
[[432. 452.]]
[[697. 518.]]
[[442. 460.]]
[[143.  34.]]
[[ 3. 52.]]
[[274. 293.]]
[[463.  66.]]
[[228. 267.]]
[[262. 268.]]
[[115.  73.]]
[[610. 506.]]
[[326. 185.]]
[[461.  44.]]
[[153.  64.]]
[[260. 378.]]
[[63. 89.]]
[[681.  53.]]
[[488.  18.]]
[[441.  34.]]
[[342. 201.]]
[[567.  72.]]
[[234. 255.]]
[[153.  36.]]
[[171.  91.]]
[[ 60. 239.]]
[[207. 256.]]
[[321. 120.]]
[[ 93. 310.]]
[[313. 197.]]
[[102. 252.]]
[[348. 255.]]
[[54. 51.]]
[[101.  45.]]
[[632. 499.]]
[[728.  60.]]
[[195.  37.]]
[[383. 252.]]
[[32. 74.]]
[[165.  39.]]
[[511. 135.]]
[[214. 268.]]
[[214. 222.]]
[[388. 2

100
[[360. 229.]]
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[258. 287.]]
[[167.  70.]]
[[353. 203.]]
[[445. 326.]]
[[114.  83.]]
[[352. 241.]]
[[664. 520.]]
[[80. 68.]]
[[107.  57.]]
[[46. 78.]]
[[466.   3.]]
[[97. 68.]]
[[171.  50.]]
[[52. 66.]]
[[375. 192.]]
[[286. 256.]]
[[ 23. 175.]]
[[348. 189.]]
[[160. 109.]]
[[91. 57.]]
[[143.  71.]]
[[417. 461.]]
[[358. 178.]]
[[343. 178.]]
[[260. 352.]]
[[664. 510.]]
[[432. 452.]]
[[275. 294.]]
[[697. 518.]]
[[143.  34.]]
[[ 3. 52.]]
[[442. 460.]]
[[463.  66.]]
[[365. 186.]]
[[326. 185.]]
[[609. 506.]]
[[115.  73.]]
[[341. 243.]]
[[681.  53.]]
[[461.  44.]]
[[153.  64.]]
[[260. 378.]]
[[239. 252.]]
[[441.  34.]]
[[64. 89.]]
[[567.  72.]]
[[488.  18.]]
[[153.  36.]]
[[ 60. 239.]]
[[171.  91.]]
[[321. 120.]]
[[216. 260.]]
[[314. 195.]]
[[109. 247.]]
[[632. 499.]]
[[101.  45.]]
[[349. 255.]]
[[54. 51.]]
[[32. 74.]]
[[165.  39.]]
[[728.  60.]]
[[511. 135.]]
[[195.  37.]]
[[342. 201.]]
[[472. 198.]]
[[118. 261.]]
[[222. 281.]]
[[327. 160.]]
[[238. 2

100
[[360. 231.]]
[[74. 83.]]
[[371.  34.]]
[[295. 249.]]
[[629. 510.]]
[[370. 226.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[80. 68.]]
[[353. 203.]]
[[352. 241.]]
[[664. 520.]]
[[107.  57.]]
[[46. 78.]]
[[52. 66.]]
[[97. 68.]]
[[466.   3.]]
[[171.  50.]]
[[ 23. 175.]]
[[154. 108.]]
[[143.  71.]]
[[343. 178.]]
[[91. 57.]]
[[417. 461.]]
[[275. 294.]]
[[375. 177.]]
[[260. 352.]]
[[664. 510.]]
[[432. 451.]]
[[697. 518.]]
[[143.  34.]]
[[442. 460.]]
[[ 3. 52.]]
[[463.  66.]]
[[378. 191.]]
[[610. 506.]]
[[115.  73.]]
[[326. 185.]]
[[260. 378.]]
[[681.  53.]]
[[234. 262.]]
[[461.  44.]]
[[153.  64.]]
[[64. 89.]]
[[441.  34.]]
[[567.  72.]]
[[488.  18.]]
[[365. 214.]]
[[153.  36.]]
[[287. 241.]]
[[ 60. 239.]]
[[171.  91.]]
[[124. 300.]]
[[265. 254.]]
[[321. 120.]]
[[632. 499.]]
[[101.  45.]]
[[122. 241.]]
[[32. 74.]]
[[388. 193.]]
[[314. 195.]]
[[242. 254.]]
[[165.  39.]]
[[728.  60.]]
[[54. 51.]]
[[511. 135.]]
[[195.  37.]]
[[215. 163.]]
[[186. 147.]]
[[348. 260.]]
[[170. 106.]]
[[285. 2

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[294. 248.]]
[[363. 229.]]
[[167.  70.]]
[[445. 326.]]
[[114.  83.]]
[[664. 520.]]
[[80. 68.]]
[[353. 203.]]
[[52. 66.]]
[[375. 192.]]
[[107.  57.]]
[[46. 78.]]
[[97. 68.]]
[[171.  50.]]
[[466.   3.]]
[[ 23. 175.]]
[[154. 108.]]
[[91. 57.]]
[[260. 352.]]
[[417. 461.]]
[[343. 178.]]
[[143.  71.]]
[[664. 510.]]
[[352. 241.]]
[[432. 452.]]
[[697. 518.]]
[[261. 253.]]
[[143.  34.]]
[[394. 176.]]
[[442. 460.]]
[[ 3. 52.]]
[[238. 251.]]
[[122. 292.]]
[[326. 185.]]
[[463.  66.]]
[[609. 506.]]
[[115.  73.]]
[[681.  53.]]
[[279. 286.]]
[[147. 294.]]
[[461.  44.]]
[[260. 378.]]
[[241. 276.]]
[[153.  64.]]
[[388. 230.]]
[[385. 191.]]
[[567.  72.]]
[[441.  34.]]
[[64. 89.]]
[[488.  18.]]
[[153.  36.]]
[[ 60. 239.]]
[[171.  91.]]
[[401. 195.]]
[[321. 120.]]
[[54. 51.]]
[[632. 499.]]
[[101.  45.]]
[[728.  60.]]
[[32. 74.]]
[[245. 212.]]
[[313. 197.]]
[[511. 135.]]
[[165.  39.]]
[[195.  37.]]
[[348. 260.]]
[[363. 189.]]
[[170. 106.]]
[[601. 201.]]
[[327. 1

100
[[74. 83.]]
[[371.  34.]]
[[362. 228.]]
[[629. 510.]]
[[375. 192.]]
[[167.  70.]]
[[293. 246.]]
[[445. 326.]]
[[286. 282.]]
[[80. 68.]]
[[664. 520.]]
[[269. 243.]]
[[289. 257.]]
[[114.  83.]]
[[353. 203.]]
[[52. 66.]]
[[46. 78.]]
[[107.  57.]]
[[97. 68.]]
[[466.   3.]]
[[171.  50.]]
[[411. 184.]]
[[260. 352.]]
[[154. 108.]]
[[91. 57.]]
[[350. 243.]]
[[417. 463.]]
[[ 23. 175.]]
[[243. 250.]]
[[343. 178.]]
[[664. 510.]]
[[143.  71.]]
[[402. 215.]]
[[372. 227.]]
[[432. 452.]]
[[266. 253.]]
[[143.  34.]]
[[697. 518.]]
[[442. 460.]]
[[ 3. 52.]]
[[326. 185.]]
[[609. 506.]]
[[115.  73.]]
[[461.  44.]]
[[421. 452.]]
[[681.  53.]]
[[153.  64.]]
[[259. 378.]]
[[567.  72.]]
[[156. 281.]]
[[464.  66.]]
[[63. 89.]]
[[441.  34.]]
[[488.  18.]]
[[126. 287.]]
[[171.  91.]]
[[153.  36.]]
[[261. 229.]]
[[ 60. 239.]]
[[321. 120.]]
[[632. 499.]]
[[101.  45.]]
[[165.  39.]]
[[54. 51.]]
[[728.  60.]]
[[269. 379.]]
[[313. 197.]]
[[32. 74.]]
[[390. 194.]]
[[195.  37.]]
[[511. 135.]]
[[245. 232.]]
[[170. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[374. 192.]]
[[301. 245.]]
[[348. 243.]]
[[167.  70.]]
[[360. 228.]]
[[445. 326.]]
[[302. 276.]]
[[664. 520.]]
[[80. 68.]]
[[114.  83.]]
[[46. 78.]]
[[353. 203.]]
[[463.  66.]]
[[52. 66.]]
[[107.  57.]]
[[97. 68.]]
[[466.   3.]]
[[171.  50.]]
[[283. 279.]]
[[154. 108.]]
[[91. 57.]]
[[271. 249.]]
[[260. 352.]]
[[342. 201.]]
[[417. 461.]]
[[143.  71.]]
[[664. 510.]]
[[ 23. 175.]]
[[293. 253.]]
[[432. 452.]]
[[697. 518.]]
[[343. 178.]]
[[143.  34.]]
[[442. 460.]]
[[ 3. 52.]]
[[372. 215.]]
[[610. 506.]]
[[115.  73.]]
[[326. 185.]]
[[159. 283.]]
[[681.  53.]]
[[136. 284.]]
[[153.  64.]]
[[461.  44.]]
[[347. 190.]]
[[260. 378.]]
[[64. 89.]]
[[567.  72.]]
[[441.  34.]]
[[488.  18.]]
[[358. 192.]]
[[171.  91.]]
[[153.  36.]]
[[392. 194.]]
[[ 60. 239.]]
[[362. 208.]]
[[255. 250.]]
[[426. 175.]]
[[728.  60.]]
[[321. 120.]]
[[632. 499.]]
[[32. 74.]]
[[165.  39.]]
[[101.  45.]]
[[54. 51.]]
[[392. 204.]]
[[313. 197.]]
[[195.  37.]]
[[511. 135.]]
[[260. 2

100
[[74. 83.]]
[[371.  34.]]
[[374. 192.]]
[[629. 510.]]
[[358. 226.]]
[[310. 240.]]
[[167.  70.]]
[[291. 269.]]
[[347. 243.]]
[[353. 203.]]
[[445. 326.]]
[[463.  66.]]
[[265. 247.]]
[[80. 68.]]
[[664. 520.]]
[[302. 276.]]
[[114.  83.]]
[[46. 78.]]
[[52. 66.]]
[[107.  57.]]
[[97. 68.]]
[[466.   3.]]
[[171.  50.]]
[[91. 57.]]
[[260. 352.]]
[[154. 108.]]
[[417. 461.]]
[[ 22. 176.]]
[[143.  71.]]
[[664. 510.]]
[[343. 178.]]
[[697. 518.]]
[[143.  34.]]
[[440. 182.]]
[[432. 452.]]
[[ 3. 52.]]
[[372. 216.]]
[[442. 460.]]
[[345. 190.]]
[[434. 219.]]
[[115.  73.]]
[[609. 506.]]
[[152. 221.]]
[[326. 185.]]
[[681.  53.]]
[[461.  44.]]
[[153.  64.]]
[[397. 208.]]
[[64. 89.]]
[[260. 378.]]
[[567.  72.]]
[[488.  18.]]
[[441.  34.]]
[[171.  91.]]
[[ 32. 173.]]
[[342. 201.]]
[[153.  36.]]
[[ 60. 239.]]
[[392. 194.]]
[[439. 172.]]
[[252. 243.]]
[[321. 120.]]
[[632. 499.]]
[[275. 245.]]
[[101.  45.]]
[[54. 51.]]
[[728.  60.]]
[[313. 197.]]
[[430. 178.]]
[[165.  39.]]
[[32. 74.]]
[[195.  37.]]
[[511. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[357. 225.]]
[[319. 232.]]
[[167.  70.]]
[[445. 326.]]
[[340. 244.]]
[[352. 241.]]
[[373. 192.]]
[[80. 68.]]
[[664. 520.]]
[[353. 203.]]
[[114.  83.]]
[[46. 78.]]
[[52. 66.]]
[[466.   3.]]
[[97. 68.]]
[[107.  57.]]
[[171.  50.]]
[[154. 108.]]
[[91. 57.]]
[[ 23. 175.]]
[[302. 275.]]
[[258. 241.]]
[[266. 350.]]
[[417. 461.]]
[[143.  71.]]
[[473.  72.]]
[[343. 178.]]
[[664. 510.]]
[[697. 518.]]
[[463.  66.]]
[[143.  34.]]
[[281. 242.]]
[[432. 452.]]
[[442. 460.]]
[[ 3. 52.]]
[[270. 245.]]
[[457. 182.]]
[[342. 201.]]
[[115.  73.]]
[[610. 506.]]
[[681.  53.]]
[[461.  44.]]
[[261. 270.]]
[[161. 217.]]
[[326. 185.]]
[[260. 378.]]
[[153.  64.]]
[[64. 89.]]
[[567.  72.]]
[[441.  34.]]
[[488.  18.]]
[[375. 222.]]
[[153.  36.]]
[[171.  91.]]
[[ 60. 239.]]
[[321. 120.]]
[[169. 137.]]
[[32. 74.]]
[[165.  39.]]
[[101.  45.]]
[[728.  60.]]
[[632. 499.]]
[[54. 51.]]
[[456. 170.]]
[[314. 195.]]
[[195.  37.]]
[[327. 160.]]
[[511. 135.]]
[[185. 147.]]
[[170. 1

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[356. 225.]]
[[167.  70.]]
[[374. 192.]]
[[445. 326.]]
[[340. 244.]]
[[80. 68.]]
[[353. 203.]]
[[114.  83.]]
[[352. 241.]]
[[664. 520.]]
[[52. 66.]]
[[46. 78.]]
[[335. 202.]]
[[97. 68.]]
[[466.   3.]]
[[107.  57.]]
[[171.  50.]]
[[154. 108.]]
[[ 22. 176.]]
[[91. 57.]]
[[417. 461.]]
[[266. 350.]]
[[343. 178.]]
[[143.  71.]]
[[664. 510.]]
[[304. 265.]]
[[322. 231.]]
[[263. 237.]]
[[697. 518.]]
[[432. 452.]]
[[372. 216.]]
[[143.  34.]]
[[ 3. 52.]]
[[476.  68.]]
[[442. 460.]]
[[463.  66.]]
[[459. 214.]]
[[115.  73.]]
[[609. 506.]]
[[260. 378.]]
[[461.  44.]]
[[326. 185.]]
[[153.  64.]]
[[681.  53.]]
[[64. 89.]]
[[270. 261.]]
[[468. 203.]]
[[567.  72.]]
[[441.  34.]]
[[286. 239.]]
[[153.  36.]]
[[488.  18.]]
[[ 32. 173.]]
[[274. 240.]]
[[175. 263.]]
[[163. 211.]]
[[321. 120.]]
[[32. 74.]]
[[171.  91.]]
[[450. 207.]]
[[392. 194.]]
[[ 60. 239.]]
[[728.  60.]]
[[467. 185.]]
[[343. 191.]]
[[266. 213.]]
[[151. 265.]]
[[311. 199.]]
[[101.  45.]]
[[165.

100
[[74. 83.]]
[[371.  34.]]
[[357. 225.]]
[[629. 510.]]
[[335. 202.]]
[[374. 192.]]
[[167.  70.]]
[[321. 230.]]
[[445. 326.]]
[[340. 244.]]
[[352. 241.]]
[[80. 68.]]
[[114.  83.]]
[[52. 66.]]
[[664. 520.]]
[[353. 203.]]
[[46. 78.]]
[[97. 68.]]
[[373. 217.]]
[[466.   3.]]
[[171.  50.]]
[[107.  57.]]
[[154. 108.]]
[[91. 57.]]
[[287. 238.]]
[[ 22. 176.]]
[[417. 461.]]
[[304. 268.]]
[[143.  71.]]
[[343. 178.]]
[[260. 352.]]
[[287. 224.]]
[[664. 510.]]
[[432. 452.]]
[[697. 518.]]
[[143.  34.]]
[[478. 173.]]
[[442. 460.]]
[[395. 215.]]
[[ 3. 52.]]
[[463.  66.]]
[[478.  66.]]
[[609. 506.]]
[[115.  73.]]
[[326. 185.]]
[[153.  64.]]
[[461.  44.]]
[[260. 378.]]
[[183. 254.]]
[[64. 89.]]
[[681.  53.]]
[[441.  34.]]
[[153.  36.]]
[[158. 262.]]
[[318. 262.]]
[[264. 235.]]
[[488.  18.]]
[[567.  72.]]
[[343. 191.]]
[[ 60. 239.]]
[[ 32. 173.]]
[[171.  91.]]
[[32. 74.]]
[[728.  60.]]
[[321. 120.]]
[[310. 240.]]
[[220. 161.]]
[[165.  39.]]
[[165. 211.]]
[[101.  45.]]
[[54. 51.]]
[[632. 499.]]
[[195.  

100
[[74. 83.]]
[[375. 211.]]
[[371.  34.]]
[[629. 510.]]
[[335. 202.]]
[[167.  70.]]
[[445. 326.]]
[[374. 192.]]
[[340. 244.]]
[[352. 241.]]
[[114.  83.]]
[[52. 66.]]
[[664. 520.]]
[[80. 68.]]
[[466.   3.]]
[[46. 78.]]
[[97. 68.]]
[[107.  57.]]
[[171.  50.]]
[[91. 57.]]
[[154. 108.]]
[[353. 203.]]
[[ 23. 175.]]
[[417. 461.]]
[[143.  71.]]
[[260. 352.]]
[[343. 178.]]
[[664. 510.]]
[[479.  66.]]
[[276. 255.]]
[[357. 215.]]
[[697. 518.]]
[[432. 452.]]
[[320. 195.]]
[[143.  34.]]
[[442. 460.]]
[[ 3. 52.]]
[[319. 261.]]
[[463.  66.]]
[[326. 185.]]
[[610. 506.]]
[[115.  73.]]
[[286. 233.]]
[[488. 179.]]
[[461.  44.]]
[[260. 378.]]
[[153.  64.]]
[[681.  53.]]
[[64. 89.]]
[[302. 222.]]
[[567.  72.]]
[[153.  36.]]
[[441.  34.]]
[[269. 193.]]
[[484. 215.]]
[[265. 231.]]
[[488.  18.]]
[[275. 234.]]
[[305. 262.]]
[[343. 191.]]
[[495. 202.]]
[[ 60. 239.]]
[[171.  91.]]
[[32. 74.]]
[[173. 209.]]
[[321. 120.]]
[[728.  60.]]
[[632. 499.]]
[[165.  39.]]
[[101.  45.]]
[[54. 51.]]
[[195.  37.]]
[[499. 2

100
[[375. 212.]]
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[374. 192.]]
[[335. 202.]]
[[167.  70.]]
[[368. 220.]]
[[445. 326.]]
[[340. 244.]]
[[352. 241.]]
[[52. 66.]]
[[80. 68.]]
[[114.  83.]]
[[664. 520.]]
[[46. 78.]]
[[97. 68.]]
[[466.   3.]]
[[107.  57.]]
[[171.  50.]]
[[319. 260.]]
[[91. 57.]]
[[160. 109.]]
[[342. 179.]]
[[275. 232.]]
[[354. 203.]]
[[ 22. 176.]]
[[417. 463.]]
[[357. 215.]]
[[260. 352.]]
[[143.  71.]]
[[664. 510.]]
[[697. 518.]]
[[432. 452.]]
[[143.  34.]]
[[ 3. 52.]]
[[442. 460.]]
[[326. 185.]]
[[262. 228.]]
[[609. 506.]]
[[463.  66.]]
[[285. 230.]]
[[307. 254.]]
[[153.  64.]]
[[484.  63.]]
[[115.  73.]]
[[681.  53.]]
[[461.  44.]]
[[303. 217.]]
[[421. 452.]]
[[494. 174.]]
[[64. 89.]]
[[567.  72.]]
[[260. 378.]]
[[313. 232.]]
[[441.  34.]]
[[153.  36.]]
[[488.  18.]]
[[499. 236.]]
[[325. 203.]]
[[484.  75.]]
[[267. 192.]]
[[32. 74.]]
[[ 60. 239.]]
[[170.  91.]]
[[489. 238.]]
[[179. 205.]]
[[ 32. 173.]]
[[349. 187.]]
[[392. 194.]]
[[319. 120.]]
[[728.  60.]]
[[632.

100
[[376. 212.]]
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[369. 220.]]
[[167.  70.]]
[[445. 326.]]
[[340. 244.]]
[[335. 202.]]
[[376. 192.]]
[[664. 520.]]
[[352. 241.]]
[[80. 68.]]
[[114.  83.]]
[[52. 66.]]
[[46. 78.]]
[[97. 68.]]
[[107.  57.]]
[[466.   3.]]
[[317. 249.]]
[[484.  58.]]
[[171.  50.]]
[[160. 109.]]
[[91. 57.]]
[[ 23. 175.]]
[[260. 352.]]
[[417. 463.]]
[[143.  71.]]
[[354. 203.]]
[[343. 178.]]
[[664. 510.]]
[[697. 518.]]
[[432. 452.]]
[[266. 224.]]
[[278. 227.]]
[[ 3. 52.]]
[[442. 460.]]
[[143.  34.]]
[[490.  76.]]
[[609. 506.]]
[[315. 185.]]
[[115.  73.]]
[[300. 214.]]
[[463.  66.]]
[[153.  64.]]
[[326. 185.]]
[[192. 242.]]
[[494. 175.]]
[[318. 259.]]
[[461.  44.]]
[[495. 185.]]
[[271. 202.]]
[[272. 254.]]
[[64. 89.]]
[[681.  53.]]
[[260. 378.]]
[[421. 452.]]
[[441.  34.]]
[[181. 194.]]
[[488.  18.]]
[[567.  72.]]
[[153.  36.]]
[[472. 197.]]
[[357. 214.]]
[[32. 74.]]
[[ 60. 239.]]
[[171.  91.]]
[[319. 120.]]
[[493. 240.]]
[[168. 244.]]
[[728.  60.]]
[[349. 187.]]
[[632.

100
[[74. 83.]]
[[371.  34.]]
[[375. 215.]]
[[629. 510.]]
[[319. 213.]]
[[167.  70.]]
[[445. 326.]]
[[340. 244.]]
[[80. 68.]]
[[52. 66.]]
[[114.  83.]]
[[352. 241.]]
[[664. 520.]]
[[46. 78.]]
[[312. 246.]]
[[97. 68.]]
[[466.   3.]]
[[483.  60.]]
[[107.  57.]]
[[171.  50.]]
[[277. 224.]]
[[160. 109.]]
[[91. 57.]]
[[260. 352.]]
[[ 23. 175.]]
[[417. 461.]]
[[143.  71.]]
[[354. 203.]]
[[143.  34.]]
[[343. 178.]]
[[664. 510.]]
[[697. 518.]]
[[432. 452.]]
[[494. 177.]]
[[492.  69.]]
[[442. 460.]]
[[ 3. 52.]]
[[463.  66.]]
[[609. 506.]]
[[326. 185.]]
[[153.  64.]]
[[115.  73.]]
[[267. 220.]]
[[193. 235.]]
[[681.  53.]]
[[461.  44.]]
[[184. 191.]]
[[64. 89.]]
[[441.  34.]]
[[567.  72.]]
[[358. 214.]]
[[260. 378.]]
[[493. 241.]]
[[153.  36.]]
[[342. 201.]]
[[488.  18.]]
[[290. 215.]]
[[505. 208.]]
[[487. 214.]]
[[ 60. 239.]]
[[373. 227.]]
[[350. 187.]]
[[32. 74.]]
[[172. 242.]]
[[269. 191.]]
[[728.  60.]]
[[464. 193.]]
[[380. 190.]]
[[195.  37.]]
[[319. 120.]]
[[632. 499.]]
[[298. 208.]]
[[171.

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[376. 216.]]
[[315. 212.]]
[[167.  70.]]
[[445. 326.]]
[[340. 244.]]
[[114.  83.]]
[[352. 241.]]
[[80. 68.]]
[[664. 520.]]
[[52. 66.]]
[[46. 78.]]
[[466.   3.]]
[[97. 68.]]
[[107.  57.]]
[[171.  50.]]
[[91. 57.]]
[[354. 203.]]
[[160. 109.]]
[[ 23. 175.]]
[[493.  56.]]
[[260. 352.]]
[[417. 461.]]
[[143.  71.]]
[[664. 510.]]
[[697. 518.]]
[[143.  34.]]
[[432. 452.]]
[[376. 182.]]
[[442. 460.]]
[[ 3. 52.]]
[[343. 178.]]
[[382. 190.]]
[[326. 185.]]
[[609. 506.]]
[[358. 215.]]
[[463.  66.]]
[[115.  73.]]
[[153.  64.]]
[[461.  44.]]
[[275. 222.]]
[[343. 189.]]
[[681.  53.]]
[[491. 182.]]
[[64. 89.]]
[[304. 246.]]
[[441.  34.]]
[[260. 378.]]
[[488.  18.]]
[[567.  72.]]
[[504. 193.]]
[[153.  36.]]
[[342. 201.]]
[[497.  78.]]
[[265. 192.]]
[[ 60. 239.]]
[[485. 245.]]
[[464. 193.]]
[[32. 74.]]
[[493. 235.]]
[[632. 499.]]
[[319. 194.]]
[[171.  91.]]
[[195.  37.]]
[[284. 248.]]
[[287. 219.]]
[[321. 120.]]
[[728.  60.]]
[[54. 51.]]
[[185. 187.]]
[[101.  

100
[[74. 83.]]
[[371.  34.]]
[[303. 234.]]
[[629. 510.]]
[[375. 215.]]
[[167.  70.]]
[[445. 326.]]
[[340. 244.]]
[[52. 66.]]
[[80. 68.]]
[[114.  83.]]
[[317. 206.]]
[[46. 78.]]
[[664. 520.]]
[[352. 241.]]
[[97. 68.]]
[[466.   3.]]
[[107.  57.]]
[[171.  50.]]
[[91. 57.]]
[[160. 109.]]
[[354. 203.]]
[[ 23. 175.]]
[[260. 352.]]
[[143.  71.]]
[[417. 461.]]
[[664. 510.]]
[[697. 518.]]
[[143.  34.]]
[[343. 178.]]
[[432. 452.]]
[[500. 192.]]
[[343. 189.]]
[[442. 460.]]
[[ 3. 52.]]
[[500.  79.]]
[[326. 185.]]
[[378. 191.]]
[[281. 241.]]
[[153.  64.]]
[[609. 506.]]
[[463.  66.]]
[[286. 197.]]
[[461.  44.]]
[[115.  73.]]
[[681.  53.]]
[[488. 183.]]
[[488.  18.]]
[[389. 219.]]
[[357. 215.]]
[[64. 89.]]
[[261. 214.]]
[[441.  34.]]
[[260. 378.]]
[[567.  72.]]
[[153.  36.]]
[[342. 201.]]
[[171.  91.]]
[[32. 74.]]
[[ 60. 239.]]
[[199. 233.]]
[[281. 216.]]
[[377. 181.]]
[[728.  60.]]
[[499.  58.]]
[[319. 120.]]
[[319. 194.]]
[[632. 499.]]
[[473. 196.]]
[[486. 225.]]
[[388. 192.]]
[[483. 237.]]
[[101.

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[167.  70.]]
[[346. 243.]]
[[445. 326.]]
[[114.  83.]]
[[664. 520.]]
[[52. 66.]]
[[80. 68.]]
[[354. 203.]]
[[46. 78.]]
[[97. 68.]]
[[466.   3.]]
[[107.  57.]]
[[171.  50.]]
[[91. 57.]]
[[160. 109.]]
[[ 22. 176.]]
[[260. 352.]]
[[417. 463.]]
[[664. 510.]]
[[143.  71.]]
[[143.  34.]]
[[507.  76.]]
[[344. 189.]]
[[697. 518.]]
[[276. 178.]]
[[478. 227.]]
[[432. 452.]]
[[343. 178.]]
[[442. 460.]]
[[485. 192.]]
[[ 3. 52.]]
[[326. 185.]]
[[315. 198.]]
[[306. 237.]]
[[153.  64.]]
[[463.  66.]]
[[609. 506.]]
[[115.  73.]]
[[461.  44.]]
[[259. 213.]]
[[421. 452.]]
[[681.  53.]]
[[355. 227.]]
[[260. 378.]]
[[501.  59.]]
[[441.  34.]]
[[64. 89.]]
[[488.  18.]]
[[382. 182.]]
[[567.  72.]]
[[153.  36.]]
[[32. 74.]]
[[342. 201.]]
[[466. 206.]]
[[ 60. 239.]]
[[283. 195.]]
[[296. 231.]]
[[171.  91.]]
[[278. 214.]]
[[199. 228.]]
[[321. 120.]]
[[ 32. 173.]]
[[372. 210.]]
[[728.  60.]]
[[632. 499.]]
[[188. 180.]]
[[101.  45.]]
[[195.  37.]]
[[477. 185.]]
[[165.

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[354. 226.]]
[[301. 226.]]
[[167.  70.]]
[[340. 244.]]
[[445. 326.]]
[[52. 66.]]
[[352. 241.]]
[[664. 520.]]
[[80. 68.]]
[[269. 229.]]
[[114.  83.]]
[[354. 203.]]
[[46. 78.]]
[[365. 221.]]
[[466.   3.]]
[[97. 68.]]
[[107.  57.]]
[[171.  50.]]
[[91. 57.]]
[[293. 232.]]
[[307. 198.]]
[[160. 109.]]
[[ 23. 175.]]
[[260. 352.]]
[[417. 463.]]
[[476. 189.]]
[[664. 510.]]
[[143.  71.]]
[[374. 188.]]
[[343. 178.]]
[[143.  34.]]
[[697. 518.]]
[[432. 452.]]
[[514.  79.]]
[[ 3. 52.]]
[[506.  59.]]
[[442. 460.]]
[[326. 185.]]
[[352. 188.]]
[[383. 182.]]
[[153.  64.]]
[[463.  66.]]
[[610. 506.]]
[[260. 378.]]
[[681.  53.]]
[[421. 452.]]
[[461.  44.]]
[[267. 211.]]
[[63. 89.]]
[[115.  73.]]
[[441.  34.]]
[[488.  18.]]
[[567.  72.]]
[[265. 173.]]
[[342. 201.]]
[[395. 217.]]
[[281. 180.]]
[[170.  91.]]
[[153.  36.]]
[[ 60. 239.]]
[[321. 120.]]
[[279. 208.]]
[[32. 74.]]
[[632. 499.]]
[[101.  45.]]
[[728.  60.]]
[[281. 196.]]
[[195.  37.]]
[[165.  39.]]
[[54. 

100
[[74. 83.]]
[[371.  34.]]
[[629. 510.]]
[[345. 243.]]
[[167.  70.]]
[[445. 326.]]
[[52. 66.]]
[[80. 68.]]
[[664. 520.]]
[[114.  83.]]
[[46. 78.]]
[[301. 196.]]
[[97. 68.]]
[[466.   3.]]
[[354. 203.]]
[[107.  57.]]
[[171.  50.]]
[[392. 222.]]
[[91. 57.]]
[[160. 109.]]
[[335. 202.]]
[[260. 352.]]
[[ 22. 176.]]
[[464. 247.]]
[[664. 510.]]
[[417. 463.]]
[[343. 178.]]
[[143.  71.]]
[[468. 195.]]
[[293. 231.]]
[[697. 518.]]
[[143.  34.]]
[[510.  61.]]
[[355. 226.]]
[[432. 452.]]
[[442. 460.]]
[[463.  66.]]
[[ 3. 52.]]
[[153.  64.]]
[[326. 185.]]
[[458. 191.]]
[[609. 506.]]
[[421. 452.]]
[[305. 184.]]
[[516.  73.]]
[[260. 378.]]
[[681.  53.]]
[[115.  73.]]
[[461.  44.]]
[[64. 89.]]
[[382. 182.]]
[[441.  34.]]
[[488.  18.]]
[[375. 226.]]
[[567.  72.]]
[[278. 194.]]
[[153.  36.]]
[[372. 189.]]
[[261. 173.]]
[[ 60. 239.]]
[[252. 200.]]
[[184. 176.]]
[[ 32. 173.]]
[[171.  91.]]
[[351. 187.]]
[[321. 120.]]
[[32. 74.]]
[[728.  60.]]
[[632. 499.]]
[[101.  45.]]
[[253. 188.]]
[[195.  37.]]
[[458.